// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: keyword_stats.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndividualKeywordHistogram struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HistogramCounts []int32                `protobuf:"zigzag32,1,rep,name=histogram_counts,json=histogramCounts" json:"histogram_counts,omitempty"` //bins, say 0 to 1.0 in chunks the size of 0.1, representing the counts of how often in each bin
	KeyWordIndex    *int32                 `protobuf:"zigzag32,2,opt,name=key_word_index,json=keyWordIndex" json:"key_word_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndividualKeywordHistogram) Reset() {
	*x = IndividualKeywordHistogram{}
	mi := &file_keyword_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndividualKeywordHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndividualKeywordHistogram) ProtoMessage() {}

func (x *IndividualKeywordHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndividualKeywordHistogram.ProtoReflect.Descriptor instead.
func (*IndividualKeywordHistogram) Descriptor() ([]byte, []int) {
	return file_keyword_stats_proto_rawDescGZIP(), []int{0}
}

func (x *IndividualKeywordHistogram) GetHistogramCounts() []int32 {
	if x != nil {
		return x.HistogramCounts
	}
	return nil
}

func (x *IndividualKeywordHistogram) GetKeyWordIndex() int32 {
	if x != nil && x.KeyWordIndex != nil {
		return *x.KeyWordIndex
	}
	return 0
}

type KeywordActivation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeCounter   *int64                 `protobuf:"zigzag64,1,opt,name=time_counter,json=timeCounter" json:"time_counter,omitempty"` //not be be confused with wall-time
	KeyWordIndex  *int32                 `protobuf:"zigzag32,2,opt,name=key_word_index,json=keyWordIndex" json:"key_word_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordActivation) Reset() {
	*x = KeywordActivation{}
	mi := &file_keyword_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordActivation) ProtoMessage() {}

func (x *KeywordActivation) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordActivation.ProtoReflect.Descriptor instead.
func (*KeywordActivation) Descriptor() ([]byte, []int) {
	return file_keyword_stats_proto_rawDescGZIP(), []int{1}
}

func (x *KeywordActivation) GetTimeCounter() int64 {
	if x != nil && x.TimeCounter != nil {
		return *x.TimeCounter
	}
	return 0
}

func (x *KeywordActivation) GetKeyWordIndex() int32 {
	if x != nil && x.KeyWordIndex != nil {
		return *x.KeyWordIndex
	}
	return 0
}

type KeywordStats struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	NetModel           *string                       `protobuf:"bytes,1,opt,name=net_model,json=netModel" json:"net_model,omitempty"`
	Histograms         []*IndividualKeywordHistogram `protobuf:"bytes,2,rep,name=histograms" json:"histograms,omitempty"`
	KeywordActivations []*KeywordActivation          `protobuf:"bytes,3,rep,name=keyword_activations,json=keywordActivations" json:"keyword_activations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeywordStats) Reset() {
	*x = KeywordStats{}
	mi := &file_keyword_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordStats) ProtoMessage() {}

func (x *KeywordStats) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordStats.ProtoReflect.Descriptor instead.
func (*KeywordStats) Descriptor() ([]byte, []int) {
	return file_keyword_stats_proto_rawDescGZIP(), []int{2}
}

func (x *KeywordStats) GetNetModel() string {
	if x != nil && x.NetModel != nil {
		return *x.NetModel
	}
	return ""
}

func (x *KeywordStats) GetHistograms() []*IndividualKeywordHistogram {
	if x != nil {
		return x.Histograms
	}
	return nil
}

func (x *KeywordStats) GetKeywordActivations() []*KeywordActivation {
	if x != nil {
		return x.KeywordActivations
	}
	return nil
}

var File_keyword_stats_proto protoreflect.FileDescriptor

const file_keyword_stats_proto_rawDesc = "" +
	"\n" +
	"\x13keyword_stats.proto\"m\n" +
	"\x1aIndividualKeywordHistogram\x12)\n" +
	"\x10histogram_counts\x18\x01 \x03(\x11R\x0fhistogramCounts\x12$\n" +
	"\x0ekey_word_index\x18\x02 \x01(\x11R\fkeyWordIndex\"\\\n" +
	"\x11KeywordActivation\x12!\n" +
	"\ftime_counter\x18\x01 \x01(\x12R\vtimeCounter\x12$\n" +
	"\x0ekey_word_index\x18\x02 \x01(\x11R\fkeyWordIndex\"\xad\x01\n" +
	"\fKeywordStats\x12\x1b\n" +
	"\tnet_model\x18\x01 \x01(\tR\bnetModel\x12;\n" +
	"\n" +
	"histograms\x18\x02 \x03(\v2\x1b.IndividualKeywordHistogramR\n" +
	"histograms\x12C\n" +
	"\x13keyword_activations\x18\x03 \x03(\v2\x12.KeywordActivationR\x12keywordActivationsBl\n" +
	"\x1acom.hello.suripu.api.inputB\x12KeywordStatsProtosZ:github.com/josephspurrier/hello-orb/orb/internal/pb/device"

var (
	file_keyword_stats_proto_rawDescOnce sync.Once
	file_keyword_stats_proto_rawDescData []byte
)

func file_keyword_stats_proto_rawDescGZIP() []byte {
	file_keyword_stats_proto_rawDescOnce.Do(func() {
		file_keyword_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keyword_stats_proto_rawDesc), len(file_keyword_stats_proto_rawDesc)))
	})
	return file_keyword_stats_proto_rawDescData
}

var file_keyword_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_keyword_stats_proto_goTypes = []any{
	(*IndividualKeywordHistogram)(nil), // 0: IndividualKeywordHistogram
	(*KeywordActivation)(nil),          // 1: KeywordActivation
	(*KeywordStats)(nil),               // 2: KeywordStats
}
var file_keyword_stats_proto_depIdxs = []int32{
	0, // 0: KeywordStats.histograms:type_name -> IndividualKeywordHistogram
	1, // 1: KeywordStats.keyword_activations:type_name -> KeywordActivation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_keyword_stats_proto_init() }
func file_keyword_stats_proto_init() {
	if File_keyword_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keyword_stats_proto_rawDesc), len(file_keyword_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyword_stats_proto_goTypes,
		DependencyIndexes: file_keyword_stats_proto_depIdxs,
		MessageInfos:      file_keyword_stats_proto_msgTypes,
	}.Build()
	File_keyword_stats_proto = out.File
	file_keyword_stats_proto_goTypes = nil
	file_keyword_stats_proto_depIdxs = nil
}
