// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: periodic.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchedPeriodicDataWifiAccessPoint_AntennaType int32

const (
	BatchedPeriodicDataWifiAccessPoint_IFA BatchedPeriodicDataWifiAccessPoint_AntennaType = 1
	BatchedPeriodicDataWifiAccessPoint_PCB BatchedPeriodicDataWifiAccessPoint_AntennaType = 2
)

// Enum value maps for BatchedPeriodicDataWifiAccessPoint_AntennaType.
var (
	BatchedPeriodicDataWifiAccessPoint_AntennaType_name = map[int32]string{
		1: "IFA",
		2: "PCB",
	}
	BatchedPeriodicDataWifiAccessPoint_AntennaType_value = map[string]int32{
		"IFA": 1,
		"PCB": 2,
	}
)

func (x BatchedPeriodicDataWifiAccessPoint_AntennaType) Enum() *BatchedPeriodicDataWifiAccessPoint_AntennaType {
	p := new(BatchedPeriodicDataWifiAccessPoint_AntennaType)
	*p = x
	return p
}

func (x BatchedPeriodicDataWifiAccessPoint_AntennaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchedPeriodicDataWifiAccessPoint_AntennaType) Descriptor() protoreflect.EnumDescriptor {
	return file_periodic_proto_enumTypes[0].Descriptor()
}

func (BatchedPeriodicDataWifiAccessPoint_AntennaType) Type() protoreflect.EnumType {
	return &file_periodic_proto_enumTypes[0]
}

func (x BatchedPeriodicDataWifiAccessPoint_AntennaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BatchedPeriodicDataWifiAccessPoint_AntennaType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BatchedPeriodicDataWifiAccessPoint_AntennaType(num)
	return nil
}

// Deprecated: Use BatchedPeriodicDataWifiAccessPoint_AntennaType.Descriptor instead.
func (BatchedPeriodicDataWifiAccessPoint_AntennaType) EnumDescriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{1, 0, 0}
}

type PeriodicData struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UnixTime    *int32                 `protobuf:"varint,1,opt,name=unix_time,json=unixTime" json:"unix_time,omitempty"`
	Light       *int32                 `protobuf:"varint,2,opt,name=light" json:"light,omitempty"`
	Temperature *int32                 `protobuf:"varint,3,opt,name=temperature" json:"temperature,omitempty"`
	Humidity    *int32                 `protobuf:"varint,4,opt,name=humidity" json:"humidity,omitempty"`
	Dust        *int32                 `protobuf:"varint,5,opt,name=dust" json:"dust,omitempty"`
	// optional string name=6;
	// optional bytes mac=7;
	LightVariability *int32 `protobuf:"varint,8,opt,name=light_variability,json=lightVariability" json:"light_variability,omitempty"`
	LightTonality    *int32 `protobuf:"varint,9,opt,name=light_tonality,json=lightTonality" json:"light_tonality,omitempty"`
	// optional int32 firmware_version=10;
	// Please do not reuse index 11, it's for the removed pill_data.
	// optional string device_id = 12;
	DustVariability              *int32                    `protobuf:"varint,13,opt,name=dust_variability,json=dustVariability" json:"dust_variability,omitempty"`
	DustMax                      *int32                    `protobuf:"varint,14,opt,name=dust_max,json=dustMax" json:"dust_max,omitempty"`
	DustMin                      *int32                    `protobuf:"varint,15,opt,name=dust_min,json=dustMin" json:"dust_min,omitempty"`
	WaveCount                    *int32                    `protobuf:"varint,16,opt,name=wave_count,json=waveCount" json:"wave_count,omitempty"`
	HoldCount                    *int32                    `protobuf:"varint,17,opt,name=hold_count,json=holdCount" json:"hold_count,omitempty"`
	AudioNumDisturbances         *int32                    `protobuf:"varint,18,opt,name=audio_num_disturbances,json=audioNumDisturbances" json:"audio_num_disturbances,omitempty"`
	AudioPeakDisturbanceEnergyDb *int32                    `protobuf:"varint,19,opt,name=audio_peak_disturbance_energy_db,json=audioPeakDisturbanceEnergyDb" json:"audio_peak_disturbance_energy_db,omitempty"`
	AudioPeakBackgroundEnergyDb  *int32                    `protobuf:"varint,20,opt,name=audio_peak_background_energy_db,json=audioPeakBackgroundEnergyDb" json:"audio_peak_background_energy_db,omitempty"`
	AudioPeakEnergyDb            *int32                    `protobuf:"varint,21,opt,name=audio_peak_energy_db,json=audioPeakEnergyDb" json:"audio_peak_energy_db,omitempty"`
	Pressure                     *uint32                   `protobuf:"varint,22,opt,name=pressure" json:"pressure,omitempty"` // in Q24.8 format (24 integer bits and 8 fractional bits). // Output value of “24674867” represents 24674867/256 = 96386.2 Pa = 963.862 hPa
	Tvoc                         *int32                    `protobuf:"varint,23,opt,name=tvoc" json:"tvoc,omitempty"`         //from 0 - 1000 ppb
	Co2                          *int32                    `protobuf:"varint,24,opt,name=co2" json:"co2,omitempty"`           //from 400 - 5000 ppm
	LightSensor                  *PeriodicDataLightData    `protobuf:"bytes,25,opt,name=light_sensor,json=lightSensor" json:"light_sensor,omitempty"`
	LightDurationMs              *int32                    `protobuf:"varint,26,opt,name=light_duration_ms,json=lightDurationMs" json:"light_duration_ms,omitempty"`
	KeywordStats                 *KeywordStats             `protobuf:"bytes,27,opt,name=keyword_stats,json=keywordStats" json:"keyword_stats,omitempty"`
	TvocVersion                  *PeriodicData_TvocVersion `protobuf:"bytes,28,opt,name=tvoc_version,json=tvocVersion" json:"tvoc_version,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PeriodicData) Reset() {
	*x = PeriodicData{}
	mi := &file_periodic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicData) ProtoMessage() {}

func (x *PeriodicData) ProtoReflect() protoreflect.Message {
	mi := &file_periodic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodicData.ProtoReflect.Descriptor instead.
func (*PeriodicData) Descriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{0}
}

func (x *PeriodicData) GetUnixTime() int32 {
	if x != nil && x.UnixTime != nil {
		return *x.UnixTime
	}
	return 0
}

func (x *PeriodicData) GetLight() int32 {
	if x != nil && x.Light != nil {
		return *x.Light
	}
	return 0
}

func (x *PeriodicData) GetTemperature() int32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *PeriodicData) GetHumidity() int32 {
	if x != nil && x.Humidity != nil {
		return *x.Humidity
	}
	return 0
}

func (x *PeriodicData) GetDust() int32 {
	if x != nil && x.Dust != nil {
		return *x.Dust
	}
	return 0
}

func (x *PeriodicData) GetLightVariability() int32 {
	if x != nil && x.LightVariability != nil {
		return *x.LightVariability
	}
	return 0
}

func (x *PeriodicData) GetLightTonality() int32 {
	if x != nil && x.LightTonality != nil {
		return *x.LightTonality
	}
	return 0
}

func (x *PeriodicData) GetDustVariability() int32 {
	if x != nil && x.DustVariability != nil {
		return *x.DustVariability
	}
	return 0
}

func (x *PeriodicData) GetDustMax() int32 {
	if x != nil && x.DustMax != nil {
		return *x.DustMax
	}
	return 0
}

func (x *PeriodicData) GetDustMin() int32 {
	if x != nil && x.DustMin != nil {
		return *x.DustMin
	}
	return 0
}

func (x *PeriodicData) GetWaveCount() int32 {
	if x != nil && x.WaveCount != nil {
		return *x.WaveCount
	}
	return 0
}

func (x *PeriodicData) GetHoldCount() int32 {
	if x != nil && x.HoldCount != nil {
		return *x.HoldCount
	}
	return 0
}

func (x *PeriodicData) GetAudioNumDisturbances() int32 {
	if x != nil && x.AudioNumDisturbances != nil {
		return *x.AudioNumDisturbances
	}
	return 0
}

func (x *PeriodicData) GetAudioPeakDisturbanceEnergyDb() int32 {
	if x != nil && x.AudioPeakDisturbanceEnergyDb != nil {
		return *x.AudioPeakDisturbanceEnergyDb
	}
	return 0
}

func (x *PeriodicData) GetAudioPeakBackgroundEnergyDb() int32 {
	if x != nil && x.AudioPeakBackgroundEnergyDb != nil {
		return *x.AudioPeakBackgroundEnergyDb
	}
	return 0
}

func (x *PeriodicData) GetAudioPeakEnergyDb() int32 {
	if x != nil && x.AudioPeakEnergyDb != nil {
		return *x.AudioPeakEnergyDb
	}
	return 0
}

func (x *PeriodicData) GetPressure() uint32 {
	if x != nil && x.Pressure != nil {
		return *x.Pressure
	}
	return 0
}

func (x *PeriodicData) GetTvoc() int32 {
	if x != nil && x.Tvoc != nil {
		return *x.Tvoc
	}
	return 0
}

func (x *PeriodicData) GetCo2() int32 {
	if x != nil && x.Co2 != nil {
		return *x.Co2
	}
	return 0
}

func (x *PeriodicData) GetLightSensor() *PeriodicDataLightData {
	if x != nil {
		return x.LightSensor
	}
	return nil
}

func (x *PeriodicData) GetLightDurationMs() int32 {
	if x != nil && x.LightDurationMs != nil {
		return *x.LightDurationMs
	}
	return 0
}

func (x *PeriodicData) GetKeywordStats() *KeywordStats {
	if x != nil {
		return x.KeywordStats
	}
	return nil
}

func (x *PeriodicData) GetTvocVersion() *PeriodicData_TvocVersion {
	if x != nil {
		return x.TvocVersion
	}
	return nil
}

type BatchedPeriodicData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            []*PeriodicData        `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	DeviceId        *string                `protobuf:"bytes,2,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	FirmwareVersion *int32                 `protobuf:"varint,3,req,name=firmware_version,json=firmwareVersion" json:"firmware_version,omitempty"`
	UptimeInSecond  *int32                 `protobuf:"varint,4,opt,name=uptime_in_second,json=uptimeInSecond" json:"uptime_in_second,omitempty"`
	// optional bool need_key = 5;
	// optional string serial = 6;
	ConnectedSsid *string `protobuf:"bytes,7,opt,name=connected_ssid,json=connectedSsid" json:"connected_ssid,omitempty"`
	// repeated wifi_access_point scan = 8;
	RingTimeAck     *string                               `protobuf:"bytes,9,opt,name=ring_time_ack,json=ringTimeAck" json:"ring_time_ack,omitempty"`
	Scan            []*BatchedPeriodicDataWifiAccessPoint `protobuf:"bytes,10,rep,name=scan" json:"scan,omitempty"`
	MessagesInQueue *int32                                `protobuf:"varint,11,opt,name=messages_in_queue,json=messagesInQueue" json:"messages_in_queue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchedPeriodicData) Reset() {
	*x = BatchedPeriodicData{}
	mi := &file_periodic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedPeriodicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedPeriodicData) ProtoMessage() {}

func (x *BatchedPeriodicData) ProtoReflect() protoreflect.Message {
	mi := &file_periodic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedPeriodicData.ProtoReflect.Descriptor instead.
func (*BatchedPeriodicData) Descriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{1}
}

func (x *BatchedPeriodicData) GetData() []*PeriodicData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BatchedPeriodicData) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *BatchedPeriodicData) GetFirmwareVersion() int32 {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return 0
}

func (x *BatchedPeriodicData) GetUptimeInSecond() int32 {
	if x != nil && x.UptimeInSecond != nil {
		return *x.UptimeInSecond
	}
	return 0
}

func (x *BatchedPeriodicData) GetConnectedSsid() string {
	if x != nil && x.ConnectedSsid != nil {
		return *x.ConnectedSsid
	}
	return ""
}

func (x *BatchedPeriodicData) GetRingTimeAck() string {
	if x != nil && x.RingTimeAck != nil {
		return *x.RingTimeAck
	}
	return ""
}

func (x *BatchedPeriodicData) GetScan() []*BatchedPeriodicDataWifiAccessPoint {
	if x != nil {
		return x.Scan
	}
	return nil
}

func (x *BatchedPeriodicData) GetMessagesInQueue() int32 {
	if x != nil && x.MessagesInQueue != nil {
		return *x.MessagesInQueue
	}
	return 0
}

type PeriodicDataLightData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             *int32                 `protobuf:"varint,1,req,name=r" json:"r,omitempty"`
	G             *int32                 `protobuf:"varint,2,req,name=g" json:"g,omitempty"`
	B             *int32                 `protobuf:"varint,3,req,name=b" json:"b,omitempty"`
	Infrared      *int32                 `protobuf:"varint,4,opt,name=infrared" json:"infrared,omitempty"`
	Clear         *int32                 `protobuf:"varint,5,opt,name=clear" json:"clear,omitempty"`
	LuxCount      *int32                 `protobuf:"varint,6,opt,name=lux_count,json=luxCount" json:"lux_count,omitempty"`
	UvCount       *int32                 `protobuf:"varint,7,opt,name=uv_count,json=uvCount" json:"uv_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodicDataLightData) Reset() {
	*x = PeriodicDataLightData{}
	mi := &file_periodic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicDataLightData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicDataLightData) ProtoMessage() {}

func (x *PeriodicDataLightData) ProtoReflect() protoreflect.Message {
	mi := &file_periodic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodicDataLightData.ProtoReflect.Descriptor instead.
func (*PeriodicDataLightData) Descriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PeriodicDataLightData) GetR() int32 {
	if x != nil && x.R != nil {
		return *x.R
	}
	return 0
}

func (x *PeriodicDataLightData) GetG() int32 {
	if x != nil && x.G != nil {
		return *x.G
	}
	return 0
}

func (x *PeriodicDataLightData) GetB() int32 {
	if x != nil && x.B != nil {
		return *x.B
	}
	return 0
}

func (x *PeriodicDataLightData) GetInfrared() int32 {
	if x != nil && x.Infrared != nil {
		return *x.Infrared
	}
	return 0
}

func (x *PeriodicDataLightData) GetClear() int32 {
	if x != nil && x.Clear != nil {
		return *x.Clear
	}
	return 0
}

func (x *PeriodicDataLightData) GetLuxCount() int32 {
	if x != nil && x.LuxCount != nil {
		return *x.LuxCount
	}
	return 0
}

func (x *PeriodicDataLightData) GetUvCount() int32 {
	if x != nil && x.UvCount != nil {
		return *x.UvCount
	}
	return 0
}

type PeriodicData_TvocVersion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TvocAppFwVersion  *uint32                `protobuf:"varint,1,opt,name=tvoc_app_fw_version,json=tvocAppFwVersion" json:"tvoc_app_fw_version,omitempty"`    // sensor application firmware version. This field needs to be compared in order to update sensor firmware
	TvocBootFwVersion *uint32                `protobuf:"varint,2,opt,name=tvoc_boot_fw_version,json=tvocBootFwVersion" json:"tvoc_boot_fw_version,omitempty"` // sensor boot firmware version.
	TvocHwVersion     *uint32                `protobuf:"varint,3,opt,name=tvoc_hw_version,json=tvocHwVersion" json:"tvoc_hw_version,omitempty"`               // sensor hardware version.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeriodicData_TvocVersion) Reset() {
	*x = PeriodicData_TvocVersion{}
	mi := &file_periodic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodicData_TvocVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodicData_TvocVersion) ProtoMessage() {}

func (x *PeriodicData_TvocVersion) ProtoReflect() protoreflect.Message {
	mi := &file_periodic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodicData_TvocVersion.ProtoReflect.Descriptor instead.
func (*PeriodicData_TvocVersion) Descriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PeriodicData_TvocVersion) GetTvocAppFwVersion() uint32 {
	if x != nil && x.TvocAppFwVersion != nil {
		return *x.TvocAppFwVersion
	}
	return 0
}

func (x *PeriodicData_TvocVersion) GetTvocBootFwVersion() uint32 {
	if x != nil && x.TvocBootFwVersion != nil {
		return *x.TvocBootFwVersion
	}
	return 0
}

func (x *PeriodicData_TvocVersion) GetTvocHwVersion() uint32 {
	if x != nil && x.TvocHwVersion != nil {
		return *x.TvocHwVersion
	}
	return 0
}

type BatchedPeriodicDataWifiAccessPoint struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Ssid          *string                                         `protobuf:"bytes,1,opt,name=ssid" json:"ssid,omitempty"`
	Rssi          *int32                                          `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	Antenna       *BatchedPeriodicDataWifiAccessPoint_AntennaType `protobuf:"varint,3,opt,name=antenna,enum=BatchedPeriodicDataWifiAccessPoint_AntennaType" json:"antenna,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedPeriodicDataWifiAccessPoint) Reset() {
	*x = BatchedPeriodicDataWifiAccessPoint{}
	mi := &file_periodic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedPeriodicDataWifiAccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedPeriodicDataWifiAccessPoint) ProtoMessage() {}

func (x *BatchedPeriodicDataWifiAccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_periodic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedPeriodicDataWifiAccessPoint.ProtoReflect.Descriptor instead.
func (*BatchedPeriodicDataWifiAccessPoint) Descriptor() ([]byte, []int) {
	return file_periodic_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BatchedPeriodicDataWifiAccessPoint) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *BatchedPeriodicDataWifiAccessPoint) GetRssi() int32 {
	if x != nil && x.Rssi != nil {
		return *x.Rssi
	}
	return 0
}

func (x *BatchedPeriodicDataWifiAccessPoint) GetAntenna() BatchedPeriodicDataWifiAccessPoint_AntennaType {
	if x != nil && x.Antenna != nil {
		return *x.Antenna
	}
	return BatchedPeriodicDataWifiAccessPoint_IFA
}

var File_periodic_proto protoreflect.FileDescriptor

const file_periodic_proto_rawDesc = "" +
	"\n" +
	"\x0eperiodic.proto\x1a\x13keyword_stats.proto\"\xd6\t\n" +
	"\rperiodic_data\x12\x1b\n" +
	"\tunix_time\x18\x01 \x01(\x05R\bunixTime\x12\x14\n" +
	"\x05light\x18\x02 \x01(\x05R\x05light\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x05R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x05R\bhumidity\x12\x12\n" +
	"\x04dust\x18\x05 \x01(\x05R\x04dust\x12+\n" +
	"\x11light_variability\x18\b \x01(\x05R\x10lightVariability\x12%\n" +
	"\x0elight_tonality\x18\t \x01(\x05R\rlightTonality\x12)\n" +
	"\x10dust_variability\x18\r \x01(\x05R\x0fdustVariability\x12\x19\n" +
	"\bdust_max\x18\x0e \x01(\x05R\adustMax\x12\x19\n" +
	"\bdust_min\x18\x0f \x01(\x05R\adustMin\x12\x1d\n" +
	"\n" +
	"wave_count\x18\x10 \x01(\x05R\twaveCount\x12\x1d\n" +
	"\n" +
	"hold_count\x18\x11 \x01(\x05R\tholdCount\x124\n" +
	"\x16audio_num_disturbances\x18\x12 \x01(\x05R\x14audioNumDisturbances\x12F\n" +
	" audio_peak_disturbance_energy_db\x18\x13 \x01(\x05R\x1caudioPeakDisturbanceEnergyDb\x12D\n" +
	"\x1faudio_peak_background_energy_db\x18\x14 \x01(\x05R\x1baudioPeakBackgroundEnergyDb\x12/\n" +
	"\x14audio_peak_energy_db\x18\x15 \x01(\x05R\x11audioPeakEnergyDb\x12\x1a\n" +
	"\bpressure\x18\x16 \x01(\rR\bpressure\x12\x12\n" +
	"\x04tvoc\x18\x17 \x01(\x05R\x04tvoc\x12\x10\n" +
	"\x03co2\x18\x18 \x01(\x05R\x03co2\x12<\n" +
	"\flight_sensor\x18\x19 \x01(\v2\x19.periodic_data.light_dataR\vlightSensor\x12*\n" +
	"\x11light_duration_ms\x18\x1a \x01(\x05R\x0flightDurationMs\x122\n" +
	"\rkeyword_stats\x18\x1b \x01(\v2\r.KeywordStatsR\fkeywordStats\x12=\n" +
	"\ftvoc_version\x18\x1c \x01(\v2\x1a.periodic_data.TvocVersionR\vtvocVersion\x1a\xa0\x01\n" +
	"\n" +
	"light_data\x12\f\n" +
	"\x01r\x18\x01 \x02(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x02 \x02(\x05R\x01g\x12\f\n" +
	"\x01b\x18\x03 \x02(\x05R\x01b\x12\x1a\n" +
	"\binfrared\x18\x04 \x01(\x05R\binfrared\x12\x14\n" +
	"\x05clear\x18\x05 \x01(\x05R\x05clear\x12\x1b\n" +
	"\tlux_count\x18\x06 \x01(\x05R\bluxCount\x12\x19\n" +
	"\buv_count\x18\a \x01(\x05R\auvCount\x1a\x95\x01\n" +
	"\vTvocVersion\x12-\n" +
	"\x13tvoc_app_fw_version\x18\x01 \x01(\rR\x10tvocAppFwVersion\x12/\n" +
	"\x14tvoc_boot_fw_version\x18\x02 \x01(\rR\x11tvocBootFwVersion\x12&\n" +
	"\x0ftvoc_hw_version\x18\x03 \x01(\rR\rtvocHwVersion\"\x91\x04\n" +
	"\x15batched_periodic_data\x12\"\n" +
	"\x04data\x18\x01 \x03(\v2\x0e.periodic_dataR\x04data\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x02(\tR\bdeviceId\x12)\n" +
	"\x10firmware_version\x18\x03 \x02(\x05R\x0ffirmwareVersion\x12(\n" +
	"\x10uptime_in_second\x18\x04 \x01(\x05R\x0euptimeInSecond\x12%\n" +
	"\x0econnected_ssid\x18\a \x01(\tR\rconnectedSsid\x12\"\n" +
	"\rring_time_ack\x18\t \x01(\tR\vringTimeAck\x12<\n" +
	"\x04scan\x18\n" +
	" \x03(\v2(.batched_periodic_data.wifi_access_pointR\x04scan\x12*\n" +
	"\x11messages_in_queue\x18\v \x01(\x05R\x0fmessagesInQueue\x1a\xac\x01\n" +
	"\x11wifi_access_point\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12\x12\n" +
	"\x04rssi\x18\x02 \x01(\x05R\x04rssi\x12N\n" +
	"\aantenna\x18\x03 \x01(\x0e24.batched_periodic_data.wifi_access_point.AntennaTypeR\aantenna\"\x1f\n" +
	"\vAntennaType\x12\a\n" +
	"\x03IFA\x10\x01\x12\a\n" +
	"\x03PCB\x10\x02Bi\n" +
	"\x1acom.hello.suripu.api.inputB\x0fDataInputProtosZ:github.com/josephspurrier/hello-orb/orb/internal/pb/device"

var (
	file_periodic_proto_rawDescOnce sync.Once
	file_periodic_proto_rawDescData []byte
)

func file_periodic_proto_rawDescGZIP() []byte {
	file_periodic_proto_rawDescOnce.Do(func() {
		file_periodic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_periodic_proto_rawDesc), len(file_periodic_proto_rawDesc)))
	})
	return file_periodic_proto_rawDescData
}

var file_periodic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_periodic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_periodic_proto_goTypes = []any{
	(BatchedPeriodicDataWifiAccessPoint_AntennaType)(0), // 0: batched_periodic_data.wifi_access_point.AntennaType
	(*PeriodicData)(nil),                       // 1: periodic_data
	(*BatchedPeriodicData)(nil),                // 2: batched_periodic_data
	(*PeriodicDataLightData)(nil),              // 3: periodic_data.light_data
	(*PeriodicData_TvocVersion)(nil),           // 4: periodic_data.TvocVersion
	(*BatchedPeriodicDataWifiAccessPoint)(nil), // 5: batched_periodic_data.wifi_access_point
	(*KeywordStats)(nil),                       // 6: KeywordStats
}
var file_periodic_proto_depIdxs = []int32{
	3, // 0: periodic_data.light_sensor:type_name -> periodic_data.light_data
	6, // 1: periodic_data.keyword_stats:type_name -> KeywordStats
	4, // 2: periodic_data.tvoc_version:type_name -> periodic_data.TvocVersion
	1, // 3: batched_periodic_data.data:type_name -> periodic_data
	5, // 4: batched_periodic_data.scan:type_name -> batched_periodic_data.wifi_access_point
	0, // 5: batched_periodic_data.wifi_access_point.antenna:type_name -> batched_periodic_data.wifi_access_point.AntennaType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_periodic_proto_init() }
func file_periodic_proto_init() {
	if File_periodic_proto != nil {
		return
	}
	file_keyword_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_periodic_proto_rawDesc), len(file_periodic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_periodic_proto_goTypes,
		DependencyIndexes: file_periodic_proto_depIdxs,
		EnumInfos:         file_periodic_proto_enumTypes,
		MessageInfos:      file_periodic_proto_msgTypes,
	}.Build()
	File_periodic_proto = out.File
	file_periodic_proto_goTypes = nil
	file_periodic_proto_depIdxs = nil
}
