// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: audio_features_control.proto

package syncresp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioFeaturesControl struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EnableKeywordFeatures *bool                  `protobuf:"varint,1,opt,name=enable_keyword_features,json=enableKeywordFeatures" json:"enable_keyword_features,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AudioFeaturesControl) Reset() {
	*x = AudioFeaturesControl{}
	mi := &file_audio_features_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFeaturesControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFeaturesControl) ProtoMessage() {}

func (x *AudioFeaturesControl) ProtoReflect() protoreflect.Message {
	mi := &file_audio_features_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFeaturesControl.ProtoReflect.Descriptor instead.
func (*AudioFeaturesControl) Descriptor() ([]byte, []int) {
	return file_audio_features_control_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFeaturesControl) GetEnableKeywordFeatures() bool {
	if x != nil && x.EnableKeywordFeatures != nil {
		return *x.EnableKeywordFeatures
	}
	return false
}

var File_audio_features_control_proto protoreflect.FileDescriptor

const file_audio_features_control_proto_rawDesc = "" +
	"\n" +
	"\x1caudio_features_control.proto\"N\n" +
	"\x14AudioFeaturesControl\x126\n" +
	"\x17enable_keyword_features\x18\x01 \x01(\bR\x15enableKeywordFeaturesBv\n" +
	"\x1acom.hello.suripu.api.audioB\x1aAudioFeaturesControlProtosZ<github.com/josephspurrier/hello-orb/orb/internal/pb/syncresp"

var (
	file_audio_features_control_proto_rawDescOnce sync.Once
	file_audio_features_control_proto_rawDescData []byte
)

func file_audio_features_control_proto_rawDescGZIP() []byte {
	file_audio_features_control_proto_rawDescOnce.Do(func() {
		file_audio_features_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_features_control_proto_rawDesc), len(file_audio_features_control_proto_rawDesc)))
	})
	return file_audio_features_control_proto_rawDescData
}

var file_audio_features_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audio_features_control_proto_goTypes = []any{
	(*AudioFeaturesControl)(nil), // 0: AudioFeaturesControl
}
var file_audio_features_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audio_features_control_proto_init() }
func file_audio_features_control_proto_init() {
	if File_audio_features_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_features_control_proto_rawDesc), len(file_audio_features_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audio_features_control_proto_goTypes,
		DependencyIndexes: file_audio_features_control_proto_depIdxs,
		MessageInfos:      file_audio_features_control_proto_msgTypes,
	}.Build()
	File_audio_features_control_proto = out.File
	file_audio_features_control_proto_goTypes = nil
	file_audio_features_control_proto_depIdxs = nil
}
