// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: audio_control.proto

package syncresp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioClassifierMessage_ClassifierType int32

const (
	AudioClassifierMessage_LINEARSVM AudioClassifierMessage_ClassifierType = 0
)

// Enum value maps for AudioClassifierMessage_ClassifierType.
var (
	AudioClassifierMessage_ClassifierType_name = map[int32]string{
		0: "LINEARSVM",
	}
	AudioClassifierMessage_ClassifierType_value = map[string]int32{
		"LINEARSVM": 0,
	}
)

func (x AudioClassifierMessage_ClassifierType) Enum() *AudioClassifierMessage_ClassifierType {
	p := new(AudioClassifierMessage_ClassifierType)
	*p = x
	return p
}

func (x AudioClassifierMessage_ClassifierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioClassifierMessage_ClassifierType) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_control_proto_enumTypes[0].Descriptor()
}

func (AudioClassifierMessage_ClassifierType) Type() protoreflect.EnumType {
	return &file_audio_control_proto_enumTypes[0]
}

func (x AudioClassifierMessage_ClassifierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AudioClassifierMessage_ClassifierType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AudioClassifierMessage_ClassifierType(num)
	return nil
}

// Deprecated: Use AudioClassifierMessage_ClassifierType.Descriptor instead.
func (AudioClassifierMessage_ClassifierType) EnumDescriptor() ([]byte, []int) {
	return file_audio_control_proto_rawDescGZIP(), []int{0, 0}
}

// turn on/off audio capture
type AudioControl_AudioCaptureAction int32

const (
	AudioControl_OFF AudioControl_AudioCaptureAction = 0
	AudioControl_ON  AudioControl_AudioCaptureAction = 1
)

// Enum value maps for AudioControl_AudioCaptureAction.
var (
	AudioControl_AudioCaptureAction_name = map[int32]string{
		0: "OFF",
		1: "ON",
	}
	AudioControl_AudioCaptureAction_value = map[string]int32{
		"OFF": 0,
		"ON":  1,
	}
)

func (x AudioControl_AudioCaptureAction) Enum() *AudioControl_AudioCaptureAction {
	p := new(AudioControl_AudioCaptureAction)
	*p = x
	return p
}

func (x AudioControl_AudioCaptureAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioControl_AudioCaptureAction) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_control_proto_enumTypes[1].Descriptor()
}

func (AudioControl_AudioCaptureAction) Type() protoreflect.EnumType {
	return &file_audio_control_proto_enumTypes[1]
}

func (x AudioControl_AudioCaptureAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AudioControl_AudioCaptureAction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AudioControl_AudioCaptureAction(num)
	return nil
}

// Deprecated: Use AudioControl_AudioCaptureAction.Descriptor instead.
func (AudioControl_AudioCaptureAction) EnumDescriptor() ([]byte, []int) {
	return file_audio_control_proto_rawDescGZIP(), []int{1, 0}
}

type AudioClassifierMessage struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Idata         []int32                                `protobuf:"zigzag32,1,rep,name=idata" json:"idata,omitempty"`
	Numclasses    *int32                                 `protobuf:"varint,2,opt,name=numclasses" json:"numclasses,omitempty"`
	Type          *AudioClassifierMessage_ClassifierType `protobuf:"varint,3,opt,name=type,enum=AudioClassifierMessage_ClassifierType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioClassifierMessage) Reset() {
	*x = AudioClassifierMessage{}
	mi := &file_audio_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioClassifierMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioClassifierMessage) ProtoMessage() {}

func (x *AudioClassifierMessage) ProtoReflect() protoreflect.Message {
	mi := &file_audio_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioClassifierMessage.ProtoReflect.Descriptor instead.
func (*AudioClassifierMessage) Descriptor() ([]byte, []int) {
	return file_audio_control_proto_rawDescGZIP(), []int{0}
}

func (x *AudioClassifierMessage) GetIdata() []int32 {
	if x != nil {
		return x.Idata
	}
	return nil
}

func (x *AudioClassifierMessage) GetNumclasses() int32 {
	if x != nil && x.Numclasses != nil {
		return *x.Numclasses
	}
	return 0
}

func (x *AudioClassifierMessage) GetType() AudioClassifierMessage_ClassifierType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AudioClassifierMessage_LINEARSVM
}

type AudioControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// minimum log2 audio energy above background noise to save off and classify.
	// 500 is a good value for this.  Raise to 1000 to be less sensitive.
	AudioMinEnergyThreshold *int32 `protobuf:"varint,1,opt,name=audio_min_energy_threshold,json=audioMinEnergyThreshold" json:"audio_min_energy_threshold,omitempty"`
	// feature vectors come in every 32ms  ( 256 / 16000Hz * 2, where the "2" is for the average 2, decimate)
	// so every 1875 feat vecs is a minute.
	AudioNumFeatVecsUntilAttemptFeatureUpload *int32 `protobuf:"varint,2,opt,name=audio_num_feat_vecs_until_attempt_feature_upload,json=audioNumFeatVecsUntilAttemptFeatureUpload" json:"audio_num_feat_vecs_until_attempt_feature_upload,omitempty"`
	// buffer size in bytes of audio features.  Note every ~330 bytes is 32 feat vecs, ergo 1 minute is about 20K
	// the buffer should be sized for your upload period
	AudioFeatBufferSize *int32 `protobuf:"varint,3,opt,name=audio_feat_buffer_size,json=audioFeatBufferSize" json:"audio_feat_buffer_size,omitempty"`
	// frames are 16ms long (256/16000).  When you detect snoring (or whatever), this is how many frames of data you want to record
	AudioRecordingPeriodInFrames *int32                           `protobuf:"varint,4,opt,name=audio_recording_period_in_frames,json=audioRecordingPeriodInFrames" json:"audio_recording_period_in_frames,omitempty"`
	AudioCaptureAction           *AudioControl_AudioCaptureAction `protobuf:"varint,8,opt,name=audio_capture_action,json=audioCaptureAction,enum=AudioControl_AudioCaptureAction" json:"audio_capture_action,omitempty"`
	AudioCaptureClassifier       *AudioClassifierMessage          `protobuf:"bytes,9,opt,name=audio_capture_classifier,json=audioCaptureClassifier" json:"audio_capture_classifier,omitempty"`
	AudioCaptureHmm              *AudioClassifierMessage          `protobuf:"bytes,10,opt,name=audio_capture_hmm,json=audioCaptureHmm" json:"audio_capture_hmm,omitempty"`
	AudioSaveRawData             *AudioControl_AudioCaptureAction `protobuf:"varint,11,opt,name=audio_save_raw_data,json=audioSaveRawData,enum=AudioControl_AudioCaptureAction" json:"audio_save_raw_data,omitempty"`
	AudioSaveFeatures            *AudioControl_AudioCaptureAction `protobuf:"varint,12,opt,name=audio_save_features,json=audioSaveFeatures,enum=AudioControl_AudioCaptureAction" json:"audio_save_features,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AudioControl) Reset() {
	*x = AudioControl{}
	mi := &file_audio_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioControl) ProtoMessage() {}

func (x *AudioControl) ProtoReflect() protoreflect.Message {
	mi := &file_audio_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioControl.ProtoReflect.Descriptor instead.
func (*AudioControl) Descriptor() ([]byte, []int) {
	return file_audio_control_proto_rawDescGZIP(), []int{1}
}

func (x *AudioControl) GetAudioMinEnergyThreshold() int32 {
	if x != nil && x.AudioMinEnergyThreshold != nil {
		return *x.AudioMinEnergyThreshold
	}
	return 0
}

func (x *AudioControl) GetAudioNumFeatVecsUntilAttemptFeatureUpload() int32 {
	if x != nil && x.AudioNumFeatVecsUntilAttemptFeatureUpload != nil {
		return *x.AudioNumFeatVecsUntilAttemptFeatureUpload
	}
	return 0
}

func (x *AudioControl) GetAudioFeatBufferSize() int32 {
	if x != nil && x.AudioFeatBufferSize != nil {
		return *x.AudioFeatBufferSize
	}
	return 0
}

func (x *AudioControl) GetAudioRecordingPeriodInFrames() int32 {
	if x != nil && x.AudioRecordingPeriodInFrames != nil {
		return *x.AudioRecordingPeriodInFrames
	}
	return 0
}

func (x *AudioControl) GetAudioCaptureAction() AudioControl_AudioCaptureAction {
	if x != nil && x.AudioCaptureAction != nil {
		return *x.AudioCaptureAction
	}
	return AudioControl_OFF
}

func (x *AudioControl) GetAudioCaptureClassifier() *AudioClassifierMessage {
	if x != nil {
		return x.AudioCaptureClassifier
	}
	return nil
}

func (x *AudioControl) GetAudioCaptureHmm() *AudioClassifierMessage {
	if x != nil {
		return x.AudioCaptureHmm
	}
	return nil
}

func (x *AudioControl) GetAudioSaveRawData() AudioControl_AudioCaptureAction {
	if x != nil && x.AudioSaveRawData != nil {
		return *x.AudioSaveRawData
	}
	return AudioControl_OFF
}

func (x *AudioControl) GetAudioSaveFeatures() AudioControl_AudioCaptureAction {
	if x != nil && x.AudioSaveFeatures != nil {
		return *x.AudioSaveFeatures
	}
	return AudioControl_OFF
}

var File_audio_control_proto protoreflect.FileDescriptor

const file_audio_control_proto_rawDesc = "" +
	"\n" +
	"\x13audio_control.proto\"\xab\x01\n" +
	"\x16AudioClassifierMessage\x12\x14\n" +
	"\x05idata\x18\x01 \x03(\x11R\x05idata\x12\x1e\n" +
	"\n" +
	"numclasses\x18\x02 \x01(\x05R\n" +
	"numclasses\x12:\n" +
	"\x04type\x18\x03 \x01(\x0e2&.AudioClassifierMessage.ClassifierTypeR\x04type\"\x1f\n" +
	"\x0eClassifierType\x12\r\n" +
	"\tLINEARSVM\x10\x00\"\xe3\x05\n" +
	"\fAudioControl\x12;\n" +
	"\x1aaudio_min_energy_threshold\x18\x01 \x01(\x05R\x17audioMinEnergyThreshold\x12c\n" +
	"0audio_num_feat_vecs_until_attempt_feature_upload\x18\x02 \x01(\x05R)audioNumFeatVecsUntilAttemptFeatureUpload\x123\n" +
	"\x16audio_feat_buffer_size\x18\x03 \x01(\x05R\x13audioFeatBufferSize\x12F\n" +
	" audio_recording_period_in_frames\x18\x04 \x01(\x05R\x1caudioRecordingPeriodInFrames\x12R\n" +
	"\x14audio_capture_action\x18\b \x01(\x0e2 .AudioControl.AudioCaptureActionR\x12audioCaptureAction\x12Q\n" +
	"\x18audio_capture_classifier\x18\t \x01(\v2\x17.AudioClassifierMessageR\x16audioCaptureClassifier\x12C\n" +
	"\x11audio_capture_hmm\x18\n" +
	" \x01(\v2\x17.AudioClassifierMessageR\x0faudioCaptureHmm\x12O\n" +
	"\x13audio_save_raw_data\x18\v \x01(\x0e2 .AudioControl.AudioCaptureActionR\x10audioSaveRawData\x12P\n" +
	"\x13audio_save_features\x18\f \x01(\x0e2 .AudioControl.AudioCaptureActionR\x11audioSaveFeatures\"%\n" +
	"\x12AudioCaptureAction\x12\a\n" +
	"\x03OFF\x10\x00\x12\x06\n" +
	"\x02ON\x10\x01Bn\n" +
	"\x1acom.hello.suripu.api.audioB\x12AudioControlProtosZ<github.com/josephspurrier/hello-orb/orb/internal/pb/syncresp"

var (
	file_audio_control_proto_rawDescOnce sync.Once
	file_audio_control_proto_rawDescData []byte
)

func file_audio_control_proto_rawDescGZIP() []byte {
	file_audio_control_proto_rawDescOnce.Do(func() {
		file_audio_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_control_proto_rawDesc), len(file_audio_control_proto_rawDesc)))
	})
	return file_audio_control_proto_rawDescData
}

var file_audio_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_audio_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audio_control_proto_goTypes = []any{
	(AudioClassifierMessage_ClassifierType)(0), // 0: AudioClassifierMessage.ClassifierType
	(AudioControl_AudioCaptureAction)(0),       // 1: AudioControl.AudioCaptureAction
	(*AudioClassifierMessage)(nil),             // 2: AudioClassifierMessage
	(*AudioControl)(nil),                       // 3: AudioControl
}
var file_audio_control_proto_depIdxs = []int32{
	0, // 0: AudioClassifierMessage.type:type_name -> AudioClassifierMessage.ClassifierType
	1, // 1: AudioControl.audio_capture_action:type_name -> AudioControl.AudioCaptureAction
	2, // 2: AudioControl.audio_capture_classifier:type_name -> AudioClassifierMessage
	2, // 3: AudioControl.audio_capture_hmm:type_name -> AudioClassifierMessage
	1, // 4: AudioControl.audio_save_raw_data:type_name -> AudioControl.AudioCaptureAction
	1, // 5: AudioControl.audio_save_features:type_name -> AudioControl.AudioCaptureAction
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_audio_control_proto_init() }
func file_audio_control_proto_init() {
	if File_audio_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_control_proto_rawDesc), len(file_audio_control_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audio_control_proto_goTypes,
		DependencyIndexes: file_audio_control_proto_depIdxs,
		EnumInfos:         file_audio_control_proto_enumTypes,
		MessageInfos:      file_audio_control_proto_msgTypes,
	}.Build()
	File_audio_control_proto = out.File
	file_audio_control_proto_goTypes = nil
	file_audio_control_proto_depIdxs = nil
}
