// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sync_response.proto

package syncresp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncResponse_RoomConditions int32

const (
	SyncResponse_IDEAL                 SyncResponse_RoomConditions = 1
	SyncResponse_WARNING               SyncResponse_RoomConditions = 2
	SyncResponse_ALERT                 SyncResponse_RoomConditions = 3
	SyncResponse_IDEAL_EXCLUDING_LIGHT SyncResponse_RoomConditions = 4
)

// Enum value maps for SyncResponse_RoomConditions.
var (
	SyncResponse_RoomConditions_name = map[int32]string{
		1: "IDEAL",
		2: "WARNING",
		3: "ALERT",
		4: "IDEAL_EXCLUDING_LIGHT",
	}
	SyncResponse_RoomConditions_value = map[string]int32{
		"IDEAL":                 1,
		"WARNING":               2,
		"ALERT":                 3,
		"IDEAL_EXCLUDING_LIGHT": 4,
	}
)

func (x SyncResponse_RoomConditions) Enum() *SyncResponse_RoomConditions {
	p := new(SyncResponse_RoomConditions)
	*p = x
	return p
}

func (x SyncResponse_RoomConditions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncResponse_RoomConditions) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_response_proto_enumTypes[0].Descriptor()
}

func (SyncResponse_RoomConditions) Type() protoreflect.EnumType {
	return &file_sync_response_proto_enumTypes[0]
}

func (x SyncResponse_RoomConditions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SyncResponse_RoomConditions) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SyncResponse_RoomConditions(num)
	return nil
}

// Deprecated: Use SyncResponse_RoomConditions.Descriptor instead.
func (SyncResponse_RoomConditions) EnumDescriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 0}
}

type SyncResponse_PairingAction_ActionType int32

const (
	SyncResponse_PairingAction_PAIR   SyncResponse_PairingAction_ActionType = 0
	SyncResponse_PairingAction_UNPAIR SyncResponse_PairingAction_ActionType = 1
)

// Enum value maps for SyncResponse_PairingAction_ActionType.
var (
	SyncResponse_PairingAction_ActionType_name = map[int32]string{
		0: "PAIR",
		1: "UNPAIR",
	}
	SyncResponse_PairingAction_ActionType_value = map[string]int32{
		"PAIR":   0,
		"UNPAIR": 1,
	}
)

func (x SyncResponse_PairingAction_ActionType) Enum() *SyncResponse_PairingAction_ActionType {
	p := new(SyncResponse_PairingAction_ActionType)
	*p = x
	return p
}

func (x SyncResponse_PairingAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncResponse_PairingAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_response_proto_enumTypes[1].Descriptor()
}

func (SyncResponse_PairingAction_ActionType) Type() protoreflect.EnumType {
	return &file_sync_response_proto_enumTypes[1]
}

func (x SyncResponse_PairingAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SyncResponse_PairingAction_ActionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SyncResponse_PairingAction_ActionType(num)
	return nil
}

// Deprecated: Use SyncResponse_PairingAction_ActionType.Descriptor instead.
func (SyncResponse_PairingAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 2, 0}
}

type SyncResponse_LEDAction_LEDActionType int32

const (
	SyncResponse_LEDAction_FADEIO SyncResponse_LEDAction_LEDActionType = 0 // quickly fade in color, wait, then quickly fade out
	SyncResponse_LEDAction_GLOW   SyncResponse_LEDAction_LEDActionType = 1 // Slowly fade in color for half duration, then slowly fade out
	SyncResponse_LEDAction_THROB  SyncResponse_LEDAction_LEDActionType = 2 // repeadedly fade in to color and out again
	SyncResponse_LEDAction_PULSAR SyncResponse_LEDAction_LEDActionType = 3 // Spining pulsar effect with quick fade in color, wait then quick fade out
	SyncResponse_LEDAction_DOUBLE SyncResponse_LEDAction_LEDActionType = 4 // Double spining pulsar effect with quick fade in color, wait then quick fade out
	SyncResponse_LEDAction_SIREN  SyncResponse_LEDAction_LEDActionType = 5 // Double spining pulsar with both colors with quick fade in, wait, then quick fade out
	SyncResponse_LEDAction_TRIPPY SyncResponse_LEDAction_LEDActionType = 6 // Randomized LED colors
	SyncResponse_LEDAction_PARTY  SyncResponse_LEDAction_LEDActionType = 7 // Party mode, fade to/from random colors
	SyncResponse_LEDAction_URL    SyncResponse_LEDAction_LEDActionType = 8 // URL to a multi color LED blink pattern definition
)

// Enum value maps for SyncResponse_LEDAction_LEDActionType.
var (
	SyncResponse_LEDAction_LEDActionType_name = map[int32]string{
		0: "FADEIO",
		1: "GLOW",
		2: "THROB",
		3: "PULSAR",
		4: "DOUBLE",
		5: "SIREN",
		6: "TRIPPY",
		7: "PARTY",
		8: "URL",
	}
	SyncResponse_LEDAction_LEDActionType_value = map[string]int32{
		"FADEIO": 0,
		"GLOW":   1,
		"THROB":  2,
		"PULSAR": 3,
		"DOUBLE": 4,
		"SIREN":  5,
		"TRIPPY": 6,
		"PARTY":  7,
		"URL":    8,
	}
)

func (x SyncResponse_LEDAction_LEDActionType) Enum() *SyncResponse_LEDAction_LEDActionType {
	p := new(SyncResponse_LEDAction_LEDActionType)
	*p = x
	return p
}

func (x SyncResponse_LEDAction_LEDActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncResponse_LEDAction_LEDActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_response_proto_enumTypes[2].Descriptor()
}

func (SyncResponse_LEDAction_LEDActionType) Type() protoreflect.EnumType {
	return &file_sync_response_proto_enumTypes[2]
}

func (x SyncResponse_LEDAction_LEDActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SyncResponse_LEDAction_LEDActionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SyncResponse_LEDAction_LEDActionType(num)
	return nil
}

// Deprecated: Use SyncResponse_LEDAction_LEDActionType.Descriptor instead.
func (SyncResponse_LEDAction_LEDActionType) EnumDescriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 5, 0}
}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional int32 upload_cycle = 1;
	// optional int32 sync_cycle = 2;
	// optional int32 acc_scan_cyle = 3;
	// optional int32 acc_sampling_interval = 4;
	// optional int32 device_sampling_interval = 5;
	Alarm *SyncResponse_Alarm `protobuf:"bytes,6,opt,name=alarm" json:"alarm,omitempty"`
	// optional PairingAction pairing_action = 7;
	WhiteNoise *SyncResponse_WhiteNoise `protobuf:"bytes,8,opt,name=white_noise,json=whiteNoise" json:"white_noise,omitempty"`
	// optional FlashAction flash_action = 9;
	ResetDevice      *bool                        `protobuf:"varint,10,opt,name=reset_device,json=resetDevice" json:"reset_device,omitempty"` // Does a factory reset!
	RoomConditions   *SyncResponse_RoomConditions `protobuf:"varint,12,opt,name=room_conditions,json=roomConditions,enum=SyncResponse_RoomConditions" json:"room_conditions,omitempty"`
	Files            []*SyncResponse_FileDownload `protobuf:"bytes,13,rep,name=files" json:"files,omitempty"`
	ResetToFactoryFw *bool                        `protobuf:"varint,14,opt,name=reset_to_factory_fw,json=resetToFactoryFw" json:"reset_to_factory_fw,omitempty"`
	AudioControl     *AudioControl                `protobuf:"bytes,15,opt,name=audio_control,json=audioControl" json:"audio_control,omitempty"`
	// optional uint32 unix_time = 16;
	// optional LEDAction led_action = 17;
	Mac                     []byte                       `protobuf:"bytes,18,opt,name=mac" json:"mac,omitempty"`
	BatchSize               *int32                       `protobuf:"varint,19,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	PillSettings            []*SyncResponse_PillSettings `protobuf:"bytes,20,rep,name=pill_settings,json=pillSettings" json:"pill_settings,omitempty"`
	ResetMcu                *bool                        `protobuf:"varint,21,opt,name=reset_mcu,json=resetMcu" json:"reset_mcu,omitempty"`
	UploadLogLevel          *uint32                      `protobuf:"varint,22,opt,name=upload_log_level,json=uploadLogLevel" json:"upload_log_level,omitempty"`
	PillBatchSize           *uint32                      `protobuf:"varint,23,opt,name=pill_batch_size,json=pillBatchSize" json:"pill_batch_size,omitempty"`
	RingTimeAck             *string                      `protobuf:"bytes,24,opt,name=ring_time_ack,json=ringTimeAck" json:"ring_time_ack,omitempty"`
	RoomConditionsLightsOff *SyncResponse_RoomConditions `protobuf:"varint,25,opt,name=room_conditions_lights_off,json=roomConditionsLightsOff,enum=SyncResponse_RoomConditions" json:"room_conditions_lights_off,omitempty"`
	AudioFeaturesControl    *AudioFeaturesControl        `protobuf:"bytes,26,opt,name=audio_features_control,json=audioFeaturesControl" json:"audio_features_control,omitempty"` //controls if features get uploaded, rates, etc.
	LightsOffThreshold      *uint32                      `protobuf:"varint,27,opt,name=lights_off_threshold,json=lightsOffThreshold" json:"lights_off_threshold,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_sync_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0}
}

func (x *SyncResponse) GetAlarm() *SyncResponse_Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

func (x *SyncResponse) GetWhiteNoise() *SyncResponse_WhiteNoise {
	if x != nil {
		return x.WhiteNoise
	}
	return nil
}

func (x *SyncResponse) GetResetDevice() bool {
	if x != nil && x.ResetDevice != nil {
		return *x.ResetDevice
	}
	return false
}

func (x *SyncResponse) GetRoomConditions() SyncResponse_RoomConditions {
	if x != nil && x.RoomConditions != nil {
		return *x.RoomConditions
	}
	return SyncResponse_IDEAL
}

func (x *SyncResponse) GetFiles() []*SyncResponse_FileDownload {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SyncResponse) GetResetToFactoryFw() bool {
	if x != nil && x.ResetToFactoryFw != nil {
		return *x.ResetToFactoryFw
	}
	return false
}

func (x *SyncResponse) GetAudioControl() *AudioControl {
	if x != nil {
		return x.AudioControl
	}
	return nil
}

func (x *SyncResponse) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *SyncResponse) GetBatchSize() int32 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *SyncResponse) GetPillSettings() []*SyncResponse_PillSettings {
	if x != nil {
		return x.PillSettings
	}
	return nil
}

func (x *SyncResponse) GetResetMcu() bool {
	if x != nil && x.ResetMcu != nil {
		return *x.ResetMcu
	}
	return false
}

func (x *SyncResponse) GetUploadLogLevel() uint32 {
	if x != nil && x.UploadLogLevel != nil {
		return *x.UploadLogLevel
	}
	return 0
}

func (x *SyncResponse) GetPillBatchSize() uint32 {
	if x != nil && x.PillBatchSize != nil {
		return *x.PillBatchSize
	}
	return 0
}

func (x *SyncResponse) GetRingTimeAck() string {
	if x != nil && x.RingTimeAck != nil {
		return *x.RingTimeAck
	}
	return ""
}

func (x *SyncResponse) GetRoomConditionsLightsOff() SyncResponse_RoomConditions {
	if x != nil && x.RoomConditionsLightsOff != nil {
		return *x.RoomConditionsLightsOff
	}
	return SyncResponse_IDEAL
}

func (x *SyncResponse) GetAudioFeaturesControl() *AudioFeaturesControl {
	if x != nil {
		return x.AudioFeaturesControl
	}
	return nil
}

func (x *SyncResponse) GetLightsOffThreshold() uint32 {
	if x != nil && x.LightsOffThreshold != nil {
		return *x.LightsOffThreshold
	}
	return 0
}

type BatchedPillSettings struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	PillSettings  []*SyncResponse_PillSettings `protobuf:"bytes,1,rep,name=pill_settings,json=pillSettings" json:"pill_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedPillSettings) Reset() {
	*x = BatchedPillSettings{}
	mi := &file_sync_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedPillSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedPillSettings) ProtoMessage() {}

func (x *BatchedPillSettings) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedPillSettings.ProtoReflect.Descriptor instead.
func (*BatchedPillSettings) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{1}
}

func (x *BatchedPillSettings) GetPillSettings() []*SyncResponse_PillSettings {
	if x != nil {
		return x.PillSettings
	}
	return nil
}

type SyncResponse_FileDownload struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Host                      *string                `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Url                       *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	CopyToSerialFlash         *bool                  `protobuf:"varint,4,opt,name=copy_to_serial_flash,json=copyToSerialFlash" json:"copy_to_serial_flash,omitempty"`
	ResetNetworkProcessor     *bool                  `protobuf:"varint,5,opt,name=reset_network_processor,json=resetNetworkProcessor" json:"reset_network_processor,omitempty"`
	ResetApplicationProcessor *bool                  `protobuf:"varint,6,opt,name=reset_application_processor,json=resetApplicationProcessor" json:"reset_application_processor,omitempty"`
	SerialFlashFilename       *string                `protobuf:"bytes,7,opt,name=serial_flash_filename,json=serialFlashFilename" json:"serial_flash_filename,omitempty"`
	SerialFlashPath           *string                `protobuf:"bytes,8,opt,name=serial_flash_path,json=serialFlashPath" json:"serial_flash_path,omitempty"`
	SdCardFilename            *string                `protobuf:"bytes,3,opt,name=sd_card_filename,json=sdCardFilename" json:"sd_card_filename,omitempty"`
	SdCardPath                *string                `protobuf:"bytes,9,opt,name=sd_card_path,json=sdCardPath" json:"sd_card_path,omitempty"`
	Sha1                      []byte                 `protobuf:"bytes,10,opt,name=sha1" json:"sha1,omitempty"`
	FileSize                  *int32                 `protobuf:"varint,11,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SyncResponse_FileDownload) Reset() {
	*x = SyncResponse_FileDownload{}
	mi := &file_sync_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_FileDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_FileDownload) ProtoMessage() {}

func (x *SyncResponse_FileDownload) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_FileDownload.ProtoReflect.Descriptor instead.
func (*SyncResponse_FileDownload) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SyncResponse_FileDownload) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetCopyToSerialFlash() bool {
	if x != nil && x.CopyToSerialFlash != nil {
		return *x.CopyToSerialFlash
	}
	return false
}

func (x *SyncResponse_FileDownload) GetResetNetworkProcessor() bool {
	if x != nil && x.ResetNetworkProcessor != nil {
		return *x.ResetNetworkProcessor
	}
	return false
}

func (x *SyncResponse_FileDownload) GetResetApplicationProcessor() bool {
	if x != nil && x.ResetApplicationProcessor != nil {
		return *x.ResetApplicationProcessor
	}
	return false
}

func (x *SyncResponse_FileDownload) GetSerialFlashFilename() string {
	if x != nil && x.SerialFlashFilename != nil {
		return *x.SerialFlashFilename
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetSerialFlashPath() string {
	if x != nil && x.SerialFlashPath != nil {
		return *x.SerialFlashPath
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetSdCardFilename() string {
	if x != nil && x.SdCardFilename != nil {
		return *x.SdCardFilename
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetSdCardPath() string {
	if x != nil && x.SdCardPath != nil {
		return *x.SdCardPath
	}
	return ""
}

func (x *SyncResponse_FileDownload) GetSha1() []byte {
	if x != nil {
		return x.Sha1
	}
	return nil
}

func (x *SyncResponse_FileDownload) GetFileSize() int32 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

type SyncResponse_Alarm struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	StartTime                 *uint32                `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"` // obselete,  use ring_offset_from_now
	EndTime                   *uint32                `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`       // obselete, use ring_offset_from_now + ring_duration
	RingtoneId                *int32                 `protobuf:"varint,3,opt,name=ringtone_id,json=ringtoneId,def=1" json:"ringtone_id,omitempty"`
	RingOffsetFromNowInSecond *int32                 `protobuf:"varint,4,opt,name=ring_offset_from_now_in_second,json=ringOffsetFromNowInSecond" json:"ring_offset_from_now_in_second,omitempty"` // This is a more fault tolerance design
	RingDurationInSecond      *int32                 `protobuf:"varint,5,opt,name=ring_duration_in_second,json=ringDurationInSecond" json:"ring_duration_in_second,omitempty"`
	RingtonePath              *string                `protobuf:"bytes,6,opt,name=ringtone_path,json=ringtonePath" json:"ringtone_path,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for SyncResponse_Alarm fields.
const (
	Default_SyncResponse_Alarm_RingtoneId = int32(1)
)

func (x *SyncResponse_Alarm) Reset() {
	*x = SyncResponse_Alarm{}
	mi := &file_sync_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_Alarm) ProtoMessage() {}

func (x *SyncResponse_Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_Alarm.ProtoReflect.Descriptor instead.
func (*SyncResponse_Alarm) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SyncResponse_Alarm) GetStartTime() uint32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *SyncResponse_Alarm) GetEndTime() uint32 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *SyncResponse_Alarm) GetRingtoneId() int32 {
	if x != nil && x.RingtoneId != nil {
		return *x.RingtoneId
	}
	return Default_SyncResponse_Alarm_RingtoneId
}

func (x *SyncResponse_Alarm) GetRingOffsetFromNowInSecond() int32 {
	if x != nil && x.RingOffsetFromNowInSecond != nil {
		return *x.RingOffsetFromNowInSecond
	}
	return 0
}

func (x *SyncResponse_Alarm) GetRingDurationInSecond() int32 {
	if x != nil && x.RingDurationInSecond != nil {
		return *x.RingDurationInSecond
	}
	return 0
}

func (x *SyncResponse_Alarm) GetRingtonePath() string {
	if x != nil && x.RingtonePath != nil {
		return *x.RingtonePath
	}
	return ""
}

type SyncResponse_PairingAction struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Ssid          *string                                `protobuf:"bytes,1,opt,name=ssid" json:"ssid,omitempty"`
	Type          *SyncResponse_PairingAction_ActionType `protobuf:"varint,2,opt,name=type,enum=SyncResponse_PairingAction_ActionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse_PairingAction) Reset() {
	*x = SyncResponse_PairingAction{}
	mi := &file_sync_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_PairingAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_PairingAction) ProtoMessage() {}

func (x *SyncResponse_PairingAction) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_PairingAction.ProtoReflect.Descriptor instead.
func (*SyncResponse_PairingAction) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SyncResponse_PairingAction) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *SyncResponse_PairingAction) GetType() SyncResponse_PairingAction_ActionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SyncResponse_PairingAction_PAIR
}

type SyncResponse_WhiteNoise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *int32                 `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime       *int32                 `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	SoundId       *int32                 `protobuf:"varint,3,opt,name=sound_id,json=soundId" json:"sound_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse_WhiteNoise) Reset() {
	*x = SyncResponse_WhiteNoise{}
	mi := &file_sync_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_WhiteNoise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_WhiteNoise) ProtoMessage() {}

func (x *SyncResponse_WhiteNoise) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_WhiteNoise.ProtoReflect.Descriptor instead.
func (*SyncResponse_WhiteNoise) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 3}
}

func (x *SyncResponse_WhiteNoise) GetStartTime() int32 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *SyncResponse_WhiteNoise) GetEndTime() int32 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *SyncResponse_WhiteNoise) GetSoundId() int32 {
	if x != nil && x.SoundId != nil {
		return *x.SoundId
	}
	return 0
}

type SyncResponse_FlashAction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Red               *int32                 `protobuf:"varint,1,opt,name=red" json:"red,omitempty"`
	Green             *int32                 `protobuf:"varint,2,opt,name=green" json:"green,omitempty"`
	Blue              *int32                 `protobuf:"varint,3,opt,name=blue" json:"blue,omitempty"`
	DelayMilliseconds *int32                 `protobuf:"varint,4,opt,name=delay_milliseconds,json=delayMilliseconds" json:"delay_milliseconds,omitempty"`
	FadeIn            *bool                  `protobuf:"varint,5,opt,name=fade_in,json=fadeIn" json:"fade_in,omitempty"`
	FadeOut           *bool                  `protobuf:"varint,6,opt,name=fade_out,json=fadeOut" json:"fade_out,omitempty"`
	Rotate            *bool                  `protobuf:"varint,7,opt,name=rotate" json:"rotate,omitempty"`
	Alpha             *int32                 `protobuf:"varint,8,opt,name=alpha" json:"alpha,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncResponse_FlashAction) Reset() {
	*x = SyncResponse_FlashAction{}
	mi := &file_sync_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_FlashAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_FlashAction) ProtoMessage() {}

func (x *SyncResponse_FlashAction) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_FlashAction.ProtoReflect.Descriptor instead.
func (*SyncResponse_FlashAction) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 4}
}

func (x *SyncResponse_FlashAction) GetRed() int32 {
	if x != nil && x.Red != nil {
		return *x.Red
	}
	return 0
}

func (x *SyncResponse_FlashAction) GetGreen() int32 {
	if x != nil && x.Green != nil {
		return *x.Green
	}
	return 0
}

func (x *SyncResponse_FlashAction) GetBlue() int32 {
	if x != nil && x.Blue != nil {
		return *x.Blue
	}
	return 0
}

func (x *SyncResponse_FlashAction) GetDelayMilliseconds() int32 {
	if x != nil && x.DelayMilliseconds != nil {
		return *x.DelayMilliseconds
	}
	return 0
}

func (x *SyncResponse_FlashAction) GetFadeIn() bool {
	if x != nil && x.FadeIn != nil {
		return *x.FadeIn
	}
	return false
}

func (x *SyncResponse_FlashAction) GetFadeOut() bool {
	if x != nil && x.FadeOut != nil {
		return *x.FadeOut
	}
	return false
}

func (x *SyncResponse_FlashAction) GetRotate() bool {
	if x != nil && x.Rotate != nil {
		return *x.Rotate
	}
	return false
}

func (x *SyncResponse_FlashAction) GetAlpha() int32 {
	if x != nil && x.Alpha != nil {
		return *x.Alpha
	}
	return 0
}

type SyncResponse_LEDAction struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	Type            *SyncResponse_LEDAction_LEDActionType `protobuf:"varint,1,opt,name=type,enum=SyncResponse_LEDAction_LEDActionType" json:"type,omitempty"`    // LED Animation type
	Url             *string                               `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`                                                 // URL string used when URL type selected
	Color           *uint32                               `protobuf:"varint,3,opt,name=color" json:"color,omitempty"`                                            // ARGB main color to fade in/out
	AltColor        *uint32                               `protobuf:"varint,4,opt,name=alt_color,json=altColor" json:"alt_color,omitempty"`                      // ARGB alternative color used in SIREN type
	DurationSeconds *int32                                `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds" json:"duration_seconds,omitempty"` // Total animation duration in seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncResponse_LEDAction) Reset() {
	*x = SyncResponse_LEDAction{}
	mi := &file_sync_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_LEDAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_LEDAction) ProtoMessage() {}

func (x *SyncResponse_LEDAction) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_LEDAction.ProtoReflect.Descriptor instead.
func (*SyncResponse_LEDAction) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 5}
}

func (x *SyncResponse_LEDAction) GetType() SyncResponse_LEDAction_LEDActionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SyncResponse_LEDAction_FADEIO
}

func (x *SyncResponse_LEDAction) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *SyncResponse_LEDAction) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

func (x *SyncResponse_LEDAction) GetAltColor() uint32 {
	if x != nil && x.AltColor != nil {
		return *x.AltColor
	}
	return 0
}

func (x *SyncResponse_LEDAction) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

type SyncResponse_PillSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PillId        *string                `protobuf:"bytes,1,opt,name=pill_id,json=pillId" json:"pill_id,omitempty"`
	PillColor     *uint32                `protobuf:"varint,2,opt,name=pill_color,json=pillColor" json:"pill_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse_PillSettings) Reset() {
	*x = SyncResponse_PillSettings{}
	mi := &file_sync_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse_PillSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse_PillSettings) ProtoMessage() {}

func (x *SyncResponse_PillSettings) ProtoReflect() protoreflect.Message {
	mi := &file_sync_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse_PillSettings.ProtoReflect.Descriptor instead.
func (*SyncResponse_PillSettings) Descriptor() ([]byte, []int) {
	return file_sync_response_proto_rawDescGZIP(), []int{0, 6}
}

func (x *SyncResponse_PillSettings) GetPillId() string {
	if x != nil && x.PillId != nil {
		return *x.PillId
	}
	return ""
}

func (x *SyncResponse_PillSettings) GetPillColor() uint32 {
	if x != nil && x.PillColor != nil {
		return *x.PillColor
	}
	return 0
}

var File_sync_response_proto protoreflect.FileDescriptor

const file_sync_response_proto_rawDesc = "" +
	"\n" +
	"\x13sync_response.proto\x1a\x13audio_control.proto\x1a\x1caudio_features_control.proto\"\xa2\x13\n" +
	"\fSyncResponse\x12)\n" +
	"\x05alarm\x18\x06 \x01(\v2\x13.SyncResponse.AlarmR\x05alarm\x129\n" +
	"\vwhite_noise\x18\b \x01(\v2\x18.SyncResponse.WhiteNoiseR\n" +
	"whiteNoise\x12!\n" +
	"\freset_device\x18\n" +
	" \x01(\bR\vresetDevice\x12E\n" +
	"\x0froom_conditions\x18\f \x01(\x0e2\x1c.SyncResponse.RoomConditionsR\x0eroomConditions\x120\n" +
	"\x05files\x18\r \x03(\v2\x1a.SyncResponse.FileDownloadR\x05files\x12-\n" +
	"\x13reset_to_factory_fw\x18\x0e \x01(\bR\x10resetToFactoryFw\x122\n" +
	"\raudio_control\x18\x0f \x01(\v2\r.AudioControlR\faudioControl\x12\x10\n" +
	"\x03mac\x18\x12 \x01(\fR\x03mac\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x13 \x01(\x05R\tbatchSize\x12?\n" +
	"\rpill_settings\x18\x14 \x03(\v2\x1a.SyncResponse.PillSettingsR\fpillSettings\x12\x1b\n" +
	"\treset_mcu\x18\x15 \x01(\bR\bresetMcu\x12(\n" +
	"\x10upload_log_level\x18\x16 \x01(\rR\x0euploadLogLevel\x12&\n" +
	"\x0fpill_batch_size\x18\x17 \x01(\rR\rpillBatchSize\x12\"\n" +
	"\rring_time_ack\x18\x18 \x01(\tR\vringTimeAck\x12Y\n" +
	"\x1aroom_conditions_lights_off\x18\x19 \x01(\x0e2\x1c.SyncResponse.RoomConditionsR\x17roomConditionsLightsOff\x12K\n" +
	"\x16audio_features_control\x18\x1a \x01(\v2\x15.AudioFeaturesControlR\x14audioFeaturesControl\x120\n" +
	"\x14lights_off_threshold\x18\x1b \x01(\rR\x12lightsOffThreshold\x1a\xba\x03\n" +
	"\fFileDownload\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12/\n" +
	"\x14copy_to_serial_flash\x18\x04 \x01(\bR\x11copyToSerialFlash\x126\n" +
	"\x17reset_network_processor\x18\x05 \x01(\bR\x15resetNetworkProcessor\x12>\n" +
	"\x1breset_application_processor\x18\x06 \x01(\bR\x19resetApplicationProcessor\x122\n" +
	"\x15serial_flash_filename\x18\a \x01(\tR\x13serialFlashFilename\x12*\n" +
	"\x11serial_flash_path\x18\b \x01(\tR\x0fserialFlashPath\x12(\n" +
	"\x10sd_card_filename\x18\x03 \x01(\tR\x0esdCardFilename\x12 \n" +
	"\fsd_card_path\x18\t \x01(\tR\n" +
	"sdCardPath\x12\x12\n" +
	"\x04sha1\x18\n" +
	" \x01(\fR\x04sha1\x12\x1b\n" +
	"\tfile_size\x18\v \x01(\x05R\bfileSize\x1a\x84\x02\n" +
	"\x05Alarm\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\rR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\rR\aendTime\x12\"\n" +
	"\vringtone_id\x18\x03 \x01(\x05:\x011R\n" +
	"ringtoneId\x12A\n" +
	"\x1ering_offset_from_now_in_second\x18\x04 \x01(\x05R\x19ringOffsetFromNowInSecond\x125\n" +
	"\x17ring_duration_in_second\x18\x05 \x01(\x05R\x14ringDurationInSecond\x12#\n" +
	"\rringtone_path\x18\x06 \x01(\tR\fringtonePath\x1a\x83\x01\n" +
	"\rPairingAction\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.SyncResponse.PairingAction.ActionTypeR\x04type\"\"\n" +
	"\n" +
	"ActionType\x12\b\n" +
	"\x04PAIR\x10\x00\x12\n" +
	"\n" +
	"\x06UNPAIR\x10\x01\x1aa\n" +
	"\n" +
	"WhiteNoise\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x05R\aendTime\x12\x19\n" +
	"\bsound_id\x18\x03 \x01(\x05R\asoundId\x1a\xda\x01\n" +
	"\vFlashAction\x12\x10\n" +
	"\x03red\x18\x01 \x01(\x05R\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\x05R\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\x05R\x04blue\x12-\n" +
	"\x12delay_milliseconds\x18\x04 \x01(\x05R\x11delayMilliseconds\x12\x17\n" +
	"\afade_in\x18\x05 \x01(\bR\x06fadeIn\x12\x19\n" +
	"\bfade_out\x18\x06 \x01(\bR\afadeOut\x12\x16\n" +
	"\x06rotate\x18\a \x01(\bR\x06rotate\x12\x14\n" +
	"\x05alpha\x18\b \x01(\x05R\x05alpha\x1a\xab\x02\n" +
	"\tLEDAction\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.SyncResponse.LEDAction.LEDActionTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05color\x18\x03 \x01(\rR\x05color\x12\x1b\n" +
	"\talt_color\x18\x04 \x01(\rR\baltColor\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x05R\x0fdurationSeconds\"s\n" +
	"\rLEDActionType\x12\n" +
	"\n" +
	"\x06FADEIO\x10\x00\x12\b\n" +
	"\x04GLOW\x10\x01\x12\t\n" +
	"\x05THROB\x10\x02\x12\n" +
	"\n" +
	"\x06PULSAR\x10\x03\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x04\x12\t\n" +
	"\x05SIREN\x10\x05\x12\n" +
	"\n" +
	"\x06TRIPPY\x10\x06\x12\t\n" +
	"\x05PARTY\x10\a\x12\a\n" +
	"\x03URL\x10\b\x1aF\n" +
	"\fPillSettings\x12\x17\n" +
	"\apill_id\x18\x01 \x01(\tR\x06pillId\x12\x1d\n" +
	"\n" +
	"pill_color\x18\x02 \x01(\rR\tpillColor\"N\n" +
	"\x0eRoomConditions\x12\t\n" +
	"\x05IDEAL\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ALERT\x10\x03\x12\x19\n" +
	"\x15IDEAL_EXCLUDING_LIGHT\x10\x04\"V\n" +
	"\x13BatchedPillSettings\x12?\n" +
	"\rpill_settings\x18\x01 \x03(\v2\x1a.SyncResponse.PillSettingsR\fpillSettingsBi\n" +
	"\x1bcom.hello.suripu.api.outputB\fOutputProtosZ<github.com/josephspurrier/hello-orb/orb/internal/pb/syncresp"

var (
	file_sync_response_proto_rawDescOnce sync.Once
	file_sync_response_proto_rawDescData []byte
)

func file_sync_response_proto_rawDescGZIP() []byte {
	file_sync_response_proto_rawDescOnce.Do(func() {
		file_sync_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_response_proto_rawDesc), len(file_sync_response_proto_rawDesc)))
	})
	return file_sync_response_proto_rawDescData
}

var file_sync_response_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sync_response_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sync_response_proto_goTypes = []any{
	(SyncResponse_RoomConditions)(0),           // 0: SyncResponse.RoomConditions
	(SyncResponse_PairingAction_ActionType)(0), // 1: SyncResponse.PairingAction.ActionType
	(SyncResponse_LEDAction_LEDActionType)(0),  // 2: SyncResponse.LEDAction.LEDActionType
	(*SyncResponse)(nil),                       // 3: SyncResponse
	(*BatchedPillSettings)(nil),                // 4: BatchedPillSettings
	(*SyncResponse_FileDownload)(nil),          // 5: SyncResponse.FileDownload
	(*SyncResponse_Alarm)(nil),                 // 6: SyncResponse.Alarm
	(*SyncResponse_PairingAction)(nil),         // 7: SyncResponse.PairingAction
	(*SyncResponse_WhiteNoise)(nil),            // 8: SyncResponse.WhiteNoise
	(*SyncResponse_FlashAction)(nil),           // 9: SyncResponse.FlashAction
	(*SyncResponse_LEDAction)(nil),             // 10: SyncResponse.LEDAction
	(*SyncResponse_PillSettings)(nil),          // 11: SyncResponse.PillSettings
	(*AudioControl)(nil),                       // 12: AudioControl
	(*AudioFeaturesControl)(nil),               // 13: AudioFeaturesControl
}
var file_sync_response_proto_depIdxs = []int32{
	6,  // 0: SyncResponse.alarm:type_name -> SyncResponse.Alarm
	8,  // 1: SyncResponse.white_noise:type_name -> SyncResponse.WhiteNoise
	0,  // 2: SyncResponse.room_conditions:type_name -> SyncResponse.RoomConditions
	5,  // 3: SyncResponse.files:type_name -> SyncResponse.FileDownload
	12, // 4: SyncResponse.audio_control:type_name -> AudioControl
	11, // 5: SyncResponse.pill_settings:type_name -> SyncResponse.PillSettings
	0,  // 6: SyncResponse.room_conditions_lights_off:type_name -> SyncResponse.RoomConditions
	13, // 7: SyncResponse.audio_features_control:type_name -> AudioFeaturesControl
	11, // 8: BatchedPillSettings.pill_settings:type_name -> SyncResponse.PillSettings
	1,  // 9: SyncResponse.PairingAction.type:type_name -> SyncResponse.PairingAction.ActionType
	2,  // 10: SyncResponse.LEDAction.type:type_name -> SyncResponse.LEDAction.LEDActionType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sync_response_proto_init() }
func file_sync_response_proto_init() {
	if File_sync_response_proto != nil {
		return
	}
	file_audio_control_proto_init()
	file_audio_features_control_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_response_proto_rawDesc), len(file_sync_response_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_response_proto_goTypes,
		DependencyIndexes: file_sync_response_proto_depIdxs,
		EnumInfos:         file_sync_response_proto_enumTypes,
		MessageInfos:      file_sync_response_proto_msgTypes,
	}.Build()
	File_sync_response_proto = out.File
	file_sync_response_proto_goTypes = nil
	file_sync_response_proto_depIdxs = nil
}
