// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: file_manifest.proto

package filesync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileManifest_FileStatusType int32

const (
	FileManifest_DOWNLOAD_COMPLETED FileManifest_FileStatusType = 0
	FileManifest_DOWNLOAD_PENDING   FileManifest_FileStatusType = 1
)

// Enum value maps for FileManifest_FileStatusType.
var (
	FileManifest_FileStatusType_name = map[int32]string{
		0: "DOWNLOAD_COMPLETED",
		1: "DOWNLOAD_PENDING",
	}
	FileManifest_FileStatusType_value = map[string]int32{
		"DOWNLOAD_COMPLETED": 0,
		"DOWNLOAD_PENDING":   1,
	}
)

func (x FileManifest_FileStatusType) Enum() *FileManifest_FileStatusType {
	p := new(FileManifest_FileStatusType)
	*p = x
	return p
}

func (x FileManifest_FileStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileManifest_FileStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_manifest_proto_enumTypes[0].Descriptor()
}

func (FileManifest_FileStatusType) Type() protoreflect.EnumType {
	return &file_file_manifest_proto_enumTypes[0]
}

func (x FileManifest_FileStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FileManifest_FileStatusType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FileManifest_FileStatusType(num)
	return nil
}

// Deprecated: Use FileManifest_FileStatusType.Descriptor instead.
func (FileManifest_FileStatusType) EnumDescriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 0}
}

type FileManifest_FileOperationError_ErrorType int32

const (
	FileManifest_FileOperationError_NO_ERROR    FileManifest_FileOperationError_ErrorType = 0
	FileManifest_FileOperationError_READ_ERROR  FileManifest_FileOperationError_ErrorType = 1
	FileManifest_FileOperationError_WRITE_ERROR FileManifest_FileOperationError_ErrorType = 2
)

// Enum value maps for FileManifest_FileOperationError_ErrorType.
var (
	FileManifest_FileOperationError_ErrorType_name = map[int32]string{
		0: "NO_ERROR",
		1: "READ_ERROR",
		2: "WRITE_ERROR",
	}
	FileManifest_FileOperationError_ErrorType_value = map[string]int32{
		"NO_ERROR":    0,
		"READ_ERROR":  1,
		"WRITE_ERROR": 2,
	}
)

func (x FileManifest_FileOperationError_ErrorType) Enum() *FileManifest_FileOperationError_ErrorType {
	p := new(FileManifest_FileOperationError_ErrorType)
	*p = x
	return p
}

func (x FileManifest_FileOperationError_ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileManifest_FileOperationError_ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_manifest_proto_enumTypes[1].Descriptor()
}

func (FileManifest_FileOperationError_ErrorType) Type() protoreflect.EnumType {
	return &file_file_manifest_proto_enumTypes[1]
}

func (x FileManifest_FileOperationError_ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FileManifest_FileOperationError_ErrorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FileManifest_FileOperationError_ErrorType(num)
	return nil
}

// Deprecated: Use FileManifest_FileOperationError_ErrorType.Descriptor instead.
func (FileManifest_FileOperationError_ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 1, 0}
}

type FileManifest struct {
	state                 protoimpl.MessageState             `protogen:"open.v1"`
	FileInfo              []*FileManifest_File               `protobuf:"bytes,1,rep,name=file_info,json=fileInfo" json:"file_info,omitempty"`
	FileStatus            *FileManifest_FileStatusType       `protobuf:"varint,2,opt,name=file_status,json=fileStatus,enum=FileManifest_FileStatusType" json:"file_status,omitempty"`     // set if there are items in the download queue which are pending
	DeviceUptimeInSeconds *uint32                            `protobuf:"varint,3,opt,name=device_uptime_in_seconds,json=deviceUptimeInSeconds" json:"device_uptime_in_seconds,omitempty"` // in seconds
	QueryDelay            *uint32                            `protobuf:"varint,4,opt,name=query_delay,json=queryDelay" json:"query_delay,omitempty"`                                      // delay between requests in minutes, set by server; on device reset: 15 minutes
	FirmwareVersion       *int32                             `protobuf:"varint,5,opt,name=firmware_version,json=firmwareVersion" json:"firmware_version,omitempty"`
	UnixTime              *int32                             `protobuf:"varint,6,opt,name=unix_time,json=unixTime" json:"unix_time,omitempty"` // time at which message was created
	LinkHealth            *FileManifest_LinkHealth           `protobuf:"bytes,7,opt,name=link_health,json=linkHealth" json:"link_health,omitempty"`
	SdCardSize            *FileManifest_MemoryInfo           `protobuf:"bytes,8,opt,name=sd_card_size,json=sdCardSize" json:"sd_card_size,omitempty"`
	ErrorInfo             []*FileManifest_FileOperationError `protobuf:"bytes,9,rep,name=error_info,json=errorInfo" json:"error_info,omitempty"` // list of all the file operation errors, per file, since last upload. Max items - 10
	SenseId               *string                            `protobuf:"bytes,10,opt,name=sense_id,json=senseId" json:"sense_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FileManifest) Reset() {
	*x = FileManifest{}
	mi := &file_file_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest) ProtoMessage() {}

func (x *FileManifest) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest.ProtoReflect.Descriptor instead.
func (*FileManifest) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *FileManifest) GetFileInfo() []*FileManifest_File {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

func (x *FileManifest) GetFileStatus() FileManifest_FileStatusType {
	if x != nil && x.FileStatus != nil {
		return *x.FileStatus
	}
	return FileManifest_DOWNLOAD_COMPLETED
}

func (x *FileManifest) GetDeviceUptimeInSeconds() uint32 {
	if x != nil && x.DeviceUptimeInSeconds != nil {
		return *x.DeviceUptimeInSeconds
	}
	return 0
}

func (x *FileManifest) GetQueryDelay() uint32 {
	if x != nil && x.QueryDelay != nil {
		return *x.QueryDelay
	}
	return 0
}

func (x *FileManifest) GetFirmwareVersion() int32 {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return 0
}

func (x *FileManifest) GetUnixTime() int32 {
	if x != nil && x.UnixTime != nil {
		return *x.UnixTime
	}
	return 0
}

func (x *FileManifest) GetLinkHealth() *FileManifest_LinkHealth {
	if x != nil {
		return x.LinkHealth
	}
	return nil
}

func (x *FileManifest) GetSdCardSize() *FileManifest_MemoryInfo {
	if x != nil {
		return x.SdCardSize
	}
	return nil
}

func (x *FileManifest) GetErrorInfo() []*FileManifest_FileOperationError {
	if x != nil {
		return x.ErrorInfo
	}
	return nil
}

func (x *FileManifest) GetSenseId() string {
	if x != nil && x.SenseId != nil {
		return *x.SenseId
	}
	return ""
}

type FileManifest_FileDownload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           *string                `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Url            *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	SdCardFilename *string                `protobuf:"bytes,3,opt,name=sd_card_filename,json=sdCardFilename" json:"sd_card_filename,omitempty"`
	SdCardPath     *string                `protobuf:"bytes,4,opt,name=sd_card_path,json=sdCardPath" json:"sd_card_path,omitempty"`
	Sha1           []byte                 `protobuf:"bytes,5,opt,name=sha1" json:"sha1,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileManifest_FileDownload) Reset() {
	*x = FileManifest_FileDownload{}
	mi := &file_file_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest_FileDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest_FileDownload) ProtoMessage() {}

func (x *FileManifest_FileDownload) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest_FileDownload.ProtoReflect.Descriptor instead.
func (*FileManifest_FileDownload) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileManifest_FileDownload) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *FileManifest_FileDownload) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *FileManifest_FileDownload) GetSdCardFilename() string {
	if x != nil && x.SdCardFilename != nil {
		return *x.SdCardFilename
	}
	return ""
}

func (x *FileManifest_FileDownload) GetSdCardPath() string {
	if x != nil && x.SdCardPath != nil {
		return *x.SdCardPath
	}
	return ""
}

func (x *FileManifest_FileDownload) GetSha1() []byte {
	if x != nil {
		return x.Sha1
	}
	return nil
}

type FileManifest_FileOperationError struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Filename      *string                                    `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	ErrType       *FileManifest_FileOperationError_ErrorType `protobuf:"varint,2,opt,name=err_type,json=errType,enum=FileManifest_FileOperationError_ErrorType" json:"err_type,omitempty"`
	ErrCode       *int32                                     `protobuf:"varint,3,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileManifest_FileOperationError) Reset() {
	*x = FileManifest_FileOperationError{}
	mi := &file_file_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest_FileOperationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest_FileOperationError) ProtoMessage() {}

func (x *FileManifest_FileOperationError) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest_FileOperationError.ProtoReflect.Descriptor instead.
func (*FileManifest_FileOperationError) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FileManifest_FileOperationError) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *FileManifest_FileOperationError) GetErrType() FileManifest_FileOperationError_ErrorType {
	if x != nil && x.ErrType != nil {
		return *x.ErrType
	}
	return FileManifest_FileOperationError_NO_ERROR
}

func (x *FileManifest_FileOperationError) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

type FileManifest_File struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	DownloadInfo  *FileManifest_FileDownload `protobuf:"bytes,1,opt,name=download_info,json=downloadInfo" json:"download_info,omitempty"`
	DeleteFile    *bool                      `protobuf:"varint,2,opt,name=delete_file,json=deleteFile" json:"delete_file,omitempty"` // set by server if has_download_info = true
	UpdateFile    *bool                      `protobuf:"varint,3,opt,name=update_file,json=updateFile" json:"update_file,omitempty"` // Set by server if file needs to be download, updated, or deleted.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileManifest_File) Reset() {
	*x = FileManifest_File{}
	mi := &file_file_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest_File) ProtoMessage() {}

func (x *FileManifest_File) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest_File.ProtoReflect.Descriptor instead.
func (*FileManifest_File) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *FileManifest_File) GetDownloadInfo() *FileManifest_FileDownload {
	if x != nil {
		return x.DownloadInfo
	}
	return nil
}

func (x *FileManifest_File) GetDeleteFile() bool {
	if x != nil && x.DeleteFile != nil {
		return *x.DeleteFile
	}
	return false
}

func (x *FileManifest_File) GetUpdateFile() bool {
	if x != nil && x.UpdateFile != nil {
		return *x.UpdateFile
	}
	return false
}

type FileManifest_LinkHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SendErrors     *uint32                `protobuf:"varint,1,opt,name=send_errors,json=sendErrors" json:"send_errors,omitempty"`               // a count of send errors that occured since the previous successful upload
	TimeToResponse *uint32                `protobuf:"varint,2,opt,name=time_to_response,json=timeToResponse" json:"time_to_response,omitempty"` // Time, in minutes, from when message is sent for transmit to when a response is received from the server
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileManifest_LinkHealth) Reset() {
	*x = FileManifest_LinkHealth{}
	mi := &file_file_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest_LinkHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest_LinkHealth) ProtoMessage() {}

func (x *FileManifest_LinkHealth) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest_LinkHealth.ProtoReflect.Descriptor instead.
func (*FileManifest_LinkHealth) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 3}
}

func (x *FileManifest_LinkHealth) GetSendErrors() uint32 {
	if x != nil && x.SendErrors != nil {
		return *x.SendErrors
	}
	return 0
}

func (x *FileManifest_LinkHealth) GetTimeToResponse() uint32 {
	if x != nil && x.TimeToResponse != nil {
		return *x.TimeToResponse
	}
	return 0
}

type FileManifest_MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalMemory   *uint32                `protobuf:"varint,1,opt,name=total_memory,json=totalMemory" json:"total_memory,omitempty"`
	FreeMemory    *uint32                `protobuf:"varint,2,opt,name=free_memory,json=freeMemory" json:"free_memory,omitempty"`            // in kilobytes
	SdCardFailure *bool                  `protobuf:"varint,3,opt,name=sd_card_failure,json=sdCardFailure" json:"sd_card_failure,omitempty"` // set when there is a complete SD card failure, false otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileManifest_MemoryInfo) Reset() {
	*x = FileManifest_MemoryInfo{}
	mi := &file_file_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileManifest_MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileManifest_MemoryInfo) ProtoMessage() {}

func (x *FileManifest_MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileManifest_MemoryInfo.ProtoReflect.Descriptor instead.
func (*FileManifest_MemoryInfo) Descriptor() ([]byte, []int) {
	return file_file_manifest_proto_rawDescGZIP(), []int{0, 4}
}

func (x *FileManifest_MemoryInfo) GetTotalMemory() uint32 {
	if x != nil && x.TotalMemory != nil {
		return *x.TotalMemory
	}
	return 0
}

func (x *FileManifest_MemoryInfo) GetFreeMemory() uint32 {
	if x != nil && x.FreeMemory != nil {
		return *x.FreeMemory
	}
	return 0
}

func (x *FileManifest_MemoryInfo) GetSdCardFailure() bool {
	if x != nil && x.SdCardFailure != nil {
		return *x.SdCardFailure
	}
	return false
}

var File_file_manifest_proto protoreflect.FileDescriptor

const file_file_manifest_proto_rawDesc = "" +
	"\n" +
	"\x13file_manifest.proto\"\xfa\t\n" +
	"\fFileManifest\x12/\n" +
	"\tfile_info\x18\x01 \x03(\v2\x12.FileManifest.FileR\bfileInfo\x12=\n" +
	"\vfile_status\x18\x02 \x01(\x0e2\x1c.FileManifest.FileStatusTypeR\n" +
	"fileStatus\x127\n" +
	"\x18device_uptime_in_seconds\x18\x03 \x01(\rR\x15deviceUptimeInSeconds\x12\x1f\n" +
	"\vquery_delay\x18\x04 \x01(\rR\n" +
	"queryDelay\x12)\n" +
	"\x10firmware_version\x18\x05 \x01(\x05R\x0ffirmwareVersion\x12\x1b\n" +
	"\tunix_time\x18\x06 \x01(\x05R\bunixTime\x129\n" +
	"\vlink_health\x18\a \x01(\v2\x18.FileManifest.LinkHealthR\n" +
	"linkHealth\x12:\n" +
	"\fsd_card_size\x18\b \x01(\v2\x18.FileManifest.MemoryInfoR\n" +
	"sdCardSize\x12?\n" +
	"\n" +
	"error_info\x18\t \x03(\v2 .FileManifest.FileOperationErrorR\terrorInfo\x12\x19\n" +
	"\bsense_id\x18\n" +
	" \x01(\tR\asenseId\x1a\x94\x01\n" +
	"\fFileDownload\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12(\n" +
	"\x10sd_card_filename\x18\x03 \x01(\tR\x0esdCardFilename\x12 \n" +
	"\fsd_card_path\x18\x04 \x01(\tR\n" +
	"sdCardPath\x12\x12\n" +
	"\x04sha1\x18\x05 \x01(\fR\x04sha1\x1a\xce\x01\n" +
	"\x12FileOperationError\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12E\n" +
	"\berr_type\x18\x02 \x01(\x0e2*.FileManifest.FileOperationError.ErrorTypeR\aerrType\x12\x19\n" +
	"\berr_code\x18\x03 \x01(\x05R\aerrCode\":\n" +
	"\tErrorType\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\x0e\n" +
	"\n" +
	"READ_ERROR\x10\x01\x12\x0f\n" +
	"\vWRITE_ERROR\x10\x02\x1a\x89\x01\n" +
	"\x04File\x12?\n" +
	"\rdownload_info\x18\x01 \x01(\v2\x1a.FileManifest.FileDownloadR\fdownloadInfo\x12\x1f\n" +
	"\vdelete_file\x18\x02 \x01(\bR\n" +
	"deleteFile\x12\x1f\n" +
	"\vupdate_file\x18\x03 \x01(\bR\n" +
	"updateFile\x1aW\n" +
	"\n" +
	"LinkHealth\x12\x1f\n" +
	"\vsend_errors\x18\x01 \x01(\rR\n" +
	"sendErrors\x12(\n" +
	"\x10time_to_response\x18\x02 \x01(\rR\x0etimeToResponse\x1ax\n" +
	"\n" +
	"MemoryInfo\x12!\n" +
	"\ftotal_memory\x18\x01 \x01(\rR\vtotalMemory\x12\x1f\n" +
	"\vfree_memory\x18\x02 \x01(\rR\n" +
	"freeMemory\x12&\n" +
	"\x0fsd_card_failure\x18\x03 \x01(\bR\rsdCardFailure\">\n" +
	"\x0eFileStatusType\x12\x16\n" +
	"\x12DOWNLOAD_COMPLETED\x10\x00\x12\x14\n" +
	"\x10DOWNLOAD_PENDING\x10\x01Bd\n" +
	"\x1acom.hello.suripu.api.inputB\bFileSyncZ<github.com/josephspurrier/hello-orb/orb/internal/pb/filesync"

var (
	file_file_manifest_proto_rawDescOnce sync.Once
	file_file_manifest_proto_rawDescData []byte
)

func file_file_manifest_proto_rawDescGZIP() []byte {
	file_file_manifest_proto_rawDescOnce.Do(func() {
		file_file_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_manifest_proto_rawDesc), len(file_file_manifest_proto_rawDesc)))
	})
	return file_file_manifest_proto_rawDescData
}

var file_file_manifest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_file_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_file_manifest_proto_goTypes = []any{
	(FileManifest_FileStatusType)(0),               // 0: FileManifest.FileStatusType
	(FileManifest_FileOperationError_ErrorType)(0), // 1: FileManifest.FileOperationError.ErrorType
	(*FileManifest)(nil),                           // 2: FileManifest
	(*FileManifest_FileDownload)(nil),              // 3: FileManifest.FileDownload
	(*FileManifest_FileOperationError)(nil),        // 4: FileManifest.FileOperationError
	(*FileManifest_File)(nil),                      // 5: FileManifest.File
	(*FileManifest_LinkHealth)(nil),                // 6: FileManifest.LinkHealth
	(*FileManifest_MemoryInfo)(nil),                // 7: FileManifest.MemoryInfo
}
var file_file_manifest_proto_depIdxs = []int32{
	5, // 0: FileManifest.file_info:type_name -> FileManifest.File
	0, // 1: FileManifest.file_status:type_name -> FileManifest.FileStatusType
	6, // 2: FileManifest.link_health:type_name -> FileManifest.LinkHealth
	7, // 3: FileManifest.sd_card_size:type_name -> FileManifest.MemoryInfo
	4, // 4: FileManifest.error_info:type_name -> FileManifest.FileOperationError
	1, // 5: FileManifest.FileOperationError.err_type:type_name -> FileManifest.FileOperationError.ErrorType
	3, // 6: FileManifest.File.download_info:type_name -> FileManifest.FileDownload
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_file_manifest_proto_init() }
func file_file_manifest_proto_init() {
	if File_file_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_manifest_proto_rawDesc), len(file_file_manifest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_manifest_proto_goTypes,
		DependencyIndexes: file_file_manifest_proto_depIdxs,
		EnumInfos:         file_file_manifest_proto_enumTypes,
		MessageInfos:      file_file_manifest_proto_msgTypes,
	}.Build()
	File_file_manifest_proto = out.File
	file_file_manifest_proto_goTypes = nil
	file_file_manifest_proto_depIdxs = nil
}
