# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ntp.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ntp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tntp.proto\x12\x05hello\"a\n\rNTPDataPacket\x12\x14\n\x0creference_ts\x18\x01 \x01(\x03\x12\x11\n\torigin_ts\x18\x02 \x01(\x03\x12\x12\n\nreceive_ts\x18\x03 \x01(\x03\x12\x13\n\x0btransmit_ts\x18\x04 \x01(\x03\x42\x1a\n\x18\x63om.hello.suripu.api.ntp')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ntp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.hello.suripu.api.ntp'
  _globals['_NTPDATAPACKET']._serialized_start=20
  _globals['_NTPDATAPACKET']._serialized_end=117
# @@protoc_insertion_point(module_scope)
