// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: state.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayingAudio    *bool                  `protobuf:"varint,1,req,name=playing_audio,json=playingAudio" json:"playing_audio,omitempty"`
	DurationSeconds *uint32                `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds" json:"duration_seconds,omitempty"` // Play for `duration` seconds. If not present, play audio indefinitely.
	FilePath        *string                `protobuf:"bytes,3,opt,name=file_path,json=filePath" json:"file_path,omitempty"`                       // Required if playing_audio is true.
	VolumePercent   *uint32                `protobuf:"varint,4,opt,name=volume_percent,json=volumePercent" json:"volume_percent,omitempty"`       // As a percent [0, 100]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AudioState) Reset() {
	*x = AudioState{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioState) ProtoMessage() {}

func (x *AudioState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioState.ProtoReflect.Descriptor instead.
func (*AudioState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *AudioState) GetPlayingAudio() bool {
	if x != nil && x.PlayingAudio != nil {
		return *x.PlayingAudio
	}
	return false
}

func (x *AudioState) GetDurationSeconds() uint32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *AudioState) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

func (x *AudioState) GetVolumePercent() uint32 {
	if x != nil && x.VolumePercent != nil {
		return *x.VolumePercent
	}
	return 0
}

type SenseState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SenseId             *string                `protobuf:"bytes,1,req,name=sense_id,json=senseId" json:"sense_id,omitempty"`
	AudioState          *AudioState            `protobuf:"bytes,2,opt,name=audio_state,json=audioState" json:"audio_state,omitempty"`
	Volume              *uint32                `protobuf:"varint,3,opt,name=volume" json:"volume,omitempty"`
	VoiceControlEnabled *bool                  `protobuf:"varint,4,opt,name=voice_control_enabled,json=voiceControlEnabled" json:"voice_control_enabled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SenseState) Reset() {
	*x = SenseState{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenseState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenseState) ProtoMessage() {}

func (x *SenseState) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenseState.ProtoReflect.Descriptor instead.
func (*SenseState) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *SenseState) GetSenseId() string {
	if x != nil && x.SenseId != nil {
		return *x.SenseId
	}
	return ""
}

func (x *SenseState) GetAudioState() *AudioState {
	if x != nil {
		return x.AudioState
	}
	return nil
}

func (x *SenseState) GetVolume() uint32 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *SenseState) GetVoiceControlEnabled() bool {
	if x != nil && x.VoiceControlEnabled != nil {
		return *x.VoiceControlEnabled
	}
	return false
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\"\xa0\x01\n" +
	"\n" +
	"AudioState\x12#\n" +
	"\rplaying_audio\x18\x01 \x02(\bR\fplayingAudio\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\rR\x0fdurationSeconds\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12%\n" +
	"\x0evolume_percent\x18\x04 \x01(\rR\rvolumePercent\"\xa1\x01\n" +
	"\n" +
	"SenseState\x12\x19\n" +
	"\bsense_id\x18\x01 \x02(\tR\asenseId\x12,\n" +
	"\vaudio_state\x18\x02 \x01(\v2\v.AudioStateR\n" +
	"audioState\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\rR\x06volume\x122\n" +
	"\x15voice_control_enabled\x18\x04 \x01(\bR\x13voiceControlEnabledBW\n" +
	"\x1acom.hello.suripu.api.inputZ9github.com/josephspurrier/hello-orb/orb/internal/pb/state"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_state_proto_goTypes = []any{
	(*AudioState)(nil), // 0: AudioState
	(*SenseState)(nil), // 1: SenseState
}
var file_state_proto_depIdxs = []int32{
	0, // 0: SenseState.audio_state:type_name -> AudioState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
