// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ntp.proto

package ntp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NTPDataPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceTs   *int64                 `protobuf:"varint,1,opt,name=reference_ts,json=referenceTs" json:"reference_ts,omitempty"`
	OriginTs      *int64                 `protobuf:"varint,2,opt,name=origin_ts,json=originTs" json:"origin_ts,omitempty"`
	ReceiveTs     *int64                 `protobuf:"varint,3,opt,name=receive_ts,json=receiveTs" json:"receive_ts,omitempty"`
	TransmitTs    *int64                 `protobuf:"varint,4,opt,name=transmit_ts,json=transmitTs" json:"transmit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NTPDataPacket) Reset() {
	*x = NTPDataPacket{}
	mi := &file_ntp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NTPDataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NTPDataPacket) ProtoMessage() {}

func (x *NTPDataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_ntp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NTPDataPacket.ProtoReflect.Descriptor instead.
func (*NTPDataPacket) Descriptor() ([]byte, []int) {
	return file_ntp_proto_rawDescGZIP(), []int{0}
}

func (x *NTPDataPacket) GetReferenceTs() int64 {
	if x != nil && x.ReferenceTs != nil {
		return *x.ReferenceTs
	}
	return 0
}

func (x *NTPDataPacket) GetOriginTs() int64 {
	if x != nil && x.OriginTs != nil {
		return *x.OriginTs
	}
	return 0
}

func (x *NTPDataPacket) GetReceiveTs() int64 {
	if x != nil && x.ReceiveTs != nil {
		return *x.ReceiveTs
	}
	return 0
}

func (x *NTPDataPacket) GetTransmitTs() int64 {
	if x != nil && x.TransmitTs != nil {
		return *x.TransmitTs
	}
	return 0
}

var File_ntp_proto protoreflect.FileDescriptor

const file_ntp_proto_rawDesc = "" +
	"\n" +
	"\tntp.proto\x12\x05hello\"\x8f\x01\n" +
	"\rNTPDataPacket\x12!\n" +
	"\freference_ts\x18\x01 \x01(\x03R\vreferenceTs\x12\x1b\n" +
	"\torigin_ts\x18\x02 \x01(\x03R\boriginTs\x12\x1d\n" +
	"\n" +
	"receive_ts\x18\x03 \x01(\x03R\treceiveTs\x12\x1f\n" +
	"\vtransmit_ts\x18\x04 \x01(\x03R\n" +
	"transmitTsBS\n" +
	"\x18com.hello.suripu.api.ntpZ7github.com/josephspurrier/hello-orb/orb/internal/pb/ntp"

var (
	file_ntp_proto_rawDescOnce sync.Once
	file_ntp_proto_rawDescData []byte
)

func file_ntp_proto_rawDescGZIP() []byte {
	file_ntp_proto_rawDescOnce.Do(func() {
		file_ntp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ntp_proto_rawDesc), len(file_ntp_proto_rawDesc)))
	})
	return file_ntp_proto_rawDescData
}

var file_ntp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ntp_proto_goTypes = []any{
	(*NTPDataPacket)(nil), // 0: hello.NTPDataPacket
}
var file_ntp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ntp_proto_init() }
func file_ntp_proto_init() {
	if File_ntp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ntp_proto_rawDesc), len(file_ntp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ntp_proto_goTypes,
		DependencyIndexes: file_ntp_proto_depIdxs,
		MessageInfos:      file_ntp_proto_msgTypes,
	}.Build()
	File_ntp_proto = out.File
	file_ntp_proto_goTypes = nil
	file_ntp_proto_depIdxs = nil
}
