// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: morpheus_ble.proto

package ble

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_TIME_OUT                    ErrorType = 0 // Internal time out, no implemented yet.
	ErrorType_NETWORK_ERROR               ErrorType = 1 // Network not available or unreachable network.
	ErrorType_DEVICE_ALREADY_PAIRED       ErrorType = 2 // User tries to paired a paired device to another account.
	ErrorType_INTERNAL_DATA_ERROR         ErrorType = 3 // Data packets corruption during BLE or SPI transfer
	ErrorType_DEVICE_DATABASE_FULL        ErrorType = 4 // No more space for device pairing.
	ErrorType_DEVICE_NO_MEMORY            ErrorType = 5 // Device run out of heap
	ErrorType_INTERNAL_OPERATION_FAILED   ErrorType = 6
	ErrorType_NO_ENDPOINT_IN_RANGE        ErrorType = 7
	ErrorType_WLAN_CONNECTION_ERROR       ErrorType = 8 //factory reset failed to remove stored wifi endpoint
	ErrorType_FAIL_TO_OBTAIN_IP           ErrorType = 9
	ErrorType_WLAN_ENDPOINT_DELETE_FAILED ErrorType = 10
	ErrorType_INVALID_ACCOUNT_ID          ErrorType = 11 //pair device command doesn't contain a valid account ID
	ErrorType_FORCE_DATA_PUSH_FAILED      ErrorType = 12 //error from pushing data after MORPHEUS_COMMAND_PUSH_DATA_AFTER_SET_TIMEZONE
	ErrorType_PROTOBUF_ENCODE_FAILED      ErrorType = 13
	ErrorType_PROTOBUF_DECODE_FAILED      ErrorType = 14
	ErrorType_SERVER_CONNECTION_TIMEOUT   ErrorType = 15
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0:  "TIME_OUT",
		1:  "NETWORK_ERROR",
		2:  "DEVICE_ALREADY_PAIRED",
		3:  "INTERNAL_DATA_ERROR",
		4:  "DEVICE_DATABASE_FULL",
		5:  "DEVICE_NO_MEMORY",
		6:  "INTERNAL_OPERATION_FAILED",
		7:  "NO_ENDPOINT_IN_RANGE",
		8:  "WLAN_CONNECTION_ERROR",
		9:  "FAIL_TO_OBTAIN_IP",
		10: "WLAN_ENDPOINT_DELETE_FAILED",
		11: "INVALID_ACCOUNT_ID",
		12: "FORCE_DATA_PUSH_FAILED",
		13: "PROTOBUF_ENCODE_FAILED",
		14: "PROTOBUF_DECODE_FAILED",
		15: "SERVER_CONNECTION_TIMEOUT",
	}
	ErrorType_value = map[string]int32{
		"TIME_OUT":                    0,
		"NETWORK_ERROR":               1,
		"DEVICE_ALREADY_PAIRED":       2,
		"INTERNAL_DATA_ERROR":         3,
		"DEVICE_DATABASE_FULL":        4,
		"DEVICE_NO_MEMORY":            5,
		"INTERNAL_OPERATION_FAILED":   6,
		"NO_ENDPOINT_IN_RANGE":        7,
		"WLAN_CONNECTION_ERROR":       8,
		"FAIL_TO_OBTAIN_IP":           9,
		"WLAN_ENDPOINT_DELETE_FAILED": 10,
		"INVALID_ACCOUNT_ID":          11,
		"FORCE_DATA_PUSH_FAILED":      12,
		"PROTOBUF_ENCODE_FAILED":      13,
		"PROTOBUF_DECODE_FAILED":      14,
		"SERVER_CONNECTION_TIMEOUT":   15,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_morpheus_ble_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_morpheus_ble_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorType(num)
	return nil
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{0}
}

type WifiConnectionState int32

const (
	WifiConnectionState_NO_WLAN_CONNECTED WifiConnectionState = 0
	WifiConnectionState_WLAN_CONNECTING   WifiConnectionState = 1
	WifiConnectionState_WLAN_CONNECTED    WifiConnectionState = 2
	WifiConnectionState_IP_RETRIEVED      WifiConnectionState = 3
	WifiConnectionState_DNS_RESOLVED      WifiConnectionState = 4
	WifiConnectionState_SOCKET_CONNECTED  WifiConnectionState = 5
	WifiConnectionState_REQUEST_SENT      WifiConnectionState = 6
	WifiConnectionState_CONNECTED         WifiConnectionState = 7
	WifiConnectionState_SSL_FAIL          WifiConnectionState = 8
	WifiConnectionState_HELLO_KEY_FAIL    WifiConnectionState = 9
	WifiConnectionState_DNS_FAILED        WifiConnectionState = 10
	WifiConnectionState_CONNECT_FAILED    WifiConnectionState = 11
)

// Enum value maps for WifiConnectionState.
var (
	WifiConnectionState_name = map[int32]string{
		0:  "NO_WLAN_CONNECTED",
		1:  "WLAN_CONNECTING",
		2:  "WLAN_CONNECTED",
		3:  "IP_RETRIEVED",
		4:  "DNS_RESOLVED",
		5:  "SOCKET_CONNECTED",
		6:  "REQUEST_SENT",
		7:  "CONNECTED",
		8:  "SSL_FAIL",
		9:  "HELLO_KEY_FAIL",
		10: "DNS_FAILED",
		11: "CONNECT_FAILED",
	}
	WifiConnectionState_value = map[string]int32{
		"NO_WLAN_CONNECTED": 0,
		"WLAN_CONNECTING":   1,
		"WLAN_CONNECTED":    2,
		"IP_RETRIEVED":      3,
		"DNS_RESOLVED":      4,
		"SOCKET_CONNECTED":  5,
		"REQUEST_SENT":      6,
		"CONNECTED":         7,
		"SSL_FAIL":          8,
		"HELLO_KEY_FAIL":    9,
		"DNS_FAILED":        10,
		"CONNECT_FAILED":    11,
	}
)

func (x WifiConnectionState) Enum() *WifiConnectionState {
	p := new(WifiConnectionState)
	*p = x
	return p
}

func (x WifiConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_morpheus_ble_proto_enumTypes[1].Descriptor()
}

func (WifiConnectionState) Type() protoreflect.EnumType {
	return &file_morpheus_ble_proto_enumTypes[1]
}

func (x WifiConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WifiConnectionState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WifiConnectionState(num)
	return nil
}

// Deprecated: Use WifiConnectionState.Descriptor instead.
func (WifiConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{1}
}

// _u8 ssid[MAXIMAL_SSID_LENGTH];
// _u8 ssid_len;
// _u8 sec_type;
// _u8 bssid[SL_BSSID_LENGTH];
// _i8 rssi;
type WifiEndpointSecType int32

const (
	WifiEndpoint_SL_SCAN_SEC_TYPE_OPEN            WifiEndpointSecType = 0
	WifiEndpoint_SL_SCAN_SEC_TYPE_WEP             WifiEndpointSecType = 1
	WifiEndpoint_SL_SCAN_SEC_TYPE_WPA             WifiEndpointSecType = 2
	WifiEndpoint_SL_WLAN_SEC_TYPE_WPS_PBC         WifiEndpointSecType = 3
	WifiEndpoint_SL_WLAN_SEC_TYPE_WPS_PIN         WifiEndpointSecType = 4
	WifiEndpoint_SL_WLAN_SEC_TYPE_WPA_ENT         WifiEndpointSecType = 5
	WifiEndpoint_SL_WLAN_SEC_TYPE_P2P_PBC         WifiEndpointSecType = 6
	WifiEndpoint_SL_WLAN_SEC_TYPE_P2P_PIN_KEYPAD  WifiEndpointSecType = 7
	WifiEndpoint_SL_WLAN_SEC_TYPE_P2P_PIN_DISPLAY WifiEndpointSecType = 8
	WifiEndpoint_SL_WLAN_SEC_TYPE_P2P_PIN_AUTO    WifiEndpointSecType = 9
	WifiEndpoint_SL_WLAN_SEC_TYPE_WEP_SHARED      WifiEndpointSecType = 10
)

// Enum value maps for WifiEndpointSecType.
var (
	WifiEndpointSecType_name = map[int32]string{
		0:  "SL_SCAN_SEC_TYPE_OPEN",
		1:  "SL_SCAN_SEC_TYPE_WEP",
		2:  "SL_SCAN_SEC_TYPE_WPA",
		3:  "SL_WLAN_SEC_TYPE_WPS_PBC",
		4:  "SL_WLAN_SEC_TYPE_WPS_PIN",
		5:  "SL_WLAN_SEC_TYPE_WPA_ENT",
		6:  "SL_WLAN_SEC_TYPE_P2P_PBC",
		7:  "SL_WLAN_SEC_TYPE_P2P_PIN_KEYPAD",
		8:  "SL_WLAN_SEC_TYPE_P2P_PIN_DISPLAY",
		9:  "SL_WLAN_SEC_TYPE_P2P_PIN_AUTO",
		10: "SL_WLAN_SEC_TYPE_WEP_SHARED",
	}
	WifiEndpointSecType_value = map[string]int32{
		"SL_SCAN_SEC_TYPE_OPEN":            0,
		"SL_SCAN_SEC_TYPE_WEP":             1,
		"SL_SCAN_SEC_TYPE_WPA":             2,
		"SL_WLAN_SEC_TYPE_WPS_PBC":         3,
		"SL_WLAN_SEC_TYPE_WPS_PIN":         4,
		"SL_WLAN_SEC_TYPE_WPA_ENT":         5,
		"SL_WLAN_SEC_TYPE_P2P_PBC":         6,
		"SL_WLAN_SEC_TYPE_P2P_PIN_KEYPAD":  7,
		"SL_WLAN_SEC_TYPE_P2P_PIN_DISPLAY": 8,
		"SL_WLAN_SEC_TYPE_P2P_PIN_AUTO":    9,
		"SL_WLAN_SEC_TYPE_WEP_SHARED":      10,
	}
)

func (x WifiEndpointSecType) Enum() *WifiEndpointSecType {
	p := new(WifiEndpointSecType)
	*p = x
	return p
}

func (x WifiEndpointSecType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiEndpointSecType) Descriptor() protoreflect.EnumDescriptor {
	return file_morpheus_ble_proto_enumTypes[2].Descriptor()
}

func (WifiEndpointSecType) Type() protoreflect.EnumType {
	return &file_morpheus_ble_proto_enumTypes[2]
}

func (x WifiEndpointSecType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *WifiEndpointSecType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = WifiEndpointSecType(num)
	return nil
}

// Deprecated: Use WifiEndpointSecType.Descriptor instead.
func (WifiEndpointSecType) EnumDescriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{0, 0}
}

type MorpheusCommand_CommandType int32

const (
	MorpheusCommand_MORPHEUS_COMMAND_SET_TIME                     MorpheusCommand_CommandType = 0
	MorpheusCommand_MORPHEUS_COMMAND_GET_TIME                     MorpheusCommand_CommandType = 1
	MorpheusCommand_MORPHEUS_COMMAND_SET_WIFI_ENDPOINT            MorpheusCommand_CommandType = 2
	MorpheusCommand_MORPHEUS_COMMAND_GET_WIFI_ENDPOINT            MorpheusCommand_CommandType = 3
	MorpheusCommand_MORPHEUS_COMMAND_SET_ALARMS                   MorpheusCommand_CommandType = 4
	MorpheusCommand_MORPHEUS_COMMAND_GET_ALARMS                   MorpheusCommand_CommandType = 5
	MorpheusCommand_MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE       MorpheusCommand_CommandType = 6
	MorpheusCommand_MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE        MorpheusCommand_CommandType = 7
	MorpheusCommand_MORPHEUS_COMMAND_START_WIFISCAN               MorpheusCommand_CommandType = 8
	MorpheusCommand_MORPHEUS_COMMAND_STOP_WIFISCAN                MorpheusCommand_CommandType = 9
	MorpheusCommand_MORPHEUS_COMMAND_GET_DEVICE_ID                MorpheusCommand_CommandType = 10
	MorpheusCommand_MORPHEUS_COMMAND_ERASE_PAIRED_PHONE           MorpheusCommand_CommandType = 11
	MorpheusCommand_MORPHEUS_COMMAND_PAIR_PILL                    MorpheusCommand_CommandType = 12
	MorpheusCommand_MORPHEUS_COMMAND_ERROR                        MorpheusCommand_CommandType = 13 // if you receive this, that means something goes wrong.
	MorpheusCommand_MORPHEUS_COMMAND_PAIR_SENSE                   MorpheusCommand_CommandType = 14
	MorpheusCommand_MORPHEUS_COMMAND_UNPAIR_PILL                  MorpheusCommand_CommandType = 15
	MorpheusCommand_MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN           MorpheusCommand_CommandType = 16
	MorpheusCommand_MORPHEUS_COMMAND_PILL_DATA                    MorpheusCommand_CommandType = 17
	MorpheusCommand_MORPHEUS_COMMAND_PILL_HEARTBEAT               MorpheusCommand_CommandType = 18
	MorpheusCommand_MORPHEUS_COMMAND_PILL_DFU_BEGIN               MorpheusCommand_CommandType = 19
	MorpheusCommand_MORPHEUS_COMMAND_FACTORY_RESET                MorpheusCommand_CommandType = 20
	MorpheusCommand_MORPHEUS_COMMAND_PILL_SHAKES                  MorpheusCommand_CommandType = 21
	MorpheusCommand_MORPHEUS_COMMAND_SYNC_DEVICE_ID               MorpheusCommand_CommandType = 22
	MorpheusCommand_MORPHEUS_COMMAND_PHONE_BLE_CONNECTED          MorpheusCommand_CommandType = 23
	MorpheusCommand_MORPHEUS_COMMAND_PHONE_BLE_BONDED             MorpheusCommand_CommandType = 24
	MorpheusCommand_MORPHEUS_COMMAND_LED_BUSY                     MorpheusCommand_CommandType = 25
	MorpheusCommand_MORPHEUS_COMMAND_LED_TRIPPY                   MorpheusCommand_CommandType = 26
	MorpheusCommand_MORPHEUS_COMMAND_LED_OPERATION_FAILED         MorpheusCommand_CommandType = 27
	MorpheusCommand_MORPHEUS_COMMAND_SCAN_WIFI                    MorpheusCommand_CommandType = 28
	MorpheusCommand_MORPHEUS_COMMAND_GET_NEXT_WIFI_AP             MorpheusCommand_CommandType = 29
	MorpheusCommand_MORPHEUS_COMMAND_LED_OPERATION_SUCCESS        MorpheusCommand_CommandType = 30
	MorpheusCommand_MORPHEUS_COMMAND_PUSH_DATA_AFTER_SET_TIMEZONE MorpheusCommand_CommandType = 31
	MorpheusCommand_MORPHEUS_COMMAND_SET_COUNTRY_CODE             MorpheusCommand_CommandType = 32
	MorpheusCommand_MORPHEUS_COMMAND_SET_SERVER_IP                MorpheusCommand_CommandType = 33
	MorpheusCommand_MORPHEUS_COMMAND_CONNECTION_STATE             MorpheusCommand_CommandType = 34
	MorpheusCommand_MORPHEUS_COMMAND_PILL_PROX_DATA               MorpheusCommand_CommandType = 35
)

// Enum value maps for MorpheusCommand_CommandType.
var (
	MorpheusCommand_CommandType_name = map[int32]string{
		0:  "MORPHEUS_COMMAND_SET_TIME",
		1:  "MORPHEUS_COMMAND_GET_TIME",
		2:  "MORPHEUS_COMMAND_SET_WIFI_ENDPOINT",
		3:  "MORPHEUS_COMMAND_GET_WIFI_ENDPOINT",
		4:  "MORPHEUS_COMMAND_SET_ALARMS",
		5:  "MORPHEUS_COMMAND_GET_ALARMS",
		6:  "MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE",
		7:  "MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE",
		8:  "MORPHEUS_COMMAND_START_WIFISCAN",
		9:  "MORPHEUS_COMMAND_STOP_WIFISCAN",
		10: "MORPHEUS_COMMAND_GET_DEVICE_ID",
		11: "MORPHEUS_COMMAND_ERASE_PAIRED_PHONE",
		12: "MORPHEUS_COMMAND_PAIR_PILL",
		13: "MORPHEUS_COMMAND_ERROR",
		14: "MORPHEUS_COMMAND_PAIR_SENSE",
		15: "MORPHEUS_COMMAND_UNPAIR_PILL",
		16: "MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN",
		17: "MORPHEUS_COMMAND_PILL_DATA",
		18: "MORPHEUS_COMMAND_PILL_HEARTBEAT",
		19: "MORPHEUS_COMMAND_PILL_DFU_BEGIN",
		20: "MORPHEUS_COMMAND_FACTORY_RESET",
		21: "MORPHEUS_COMMAND_PILL_SHAKES",
		22: "MORPHEUS_COMMAND_SYNC_DEVICE_ID",
		23: "MORPHEUS_COMMAND_PHONE_BLE_CONNECTED",
		24: "MORPHEUS_COMMAND_PHONE_BLE_BONDED",
		25: "MORPHEUS_COMMAND_LED_BUSY",
		26: "MORPHEUS_COMMAND_LED_TRIPPY",
		27: "MORPHEUS_COMMAND_LED_OPERATION_FAILED",
		28: "MORPHEUS_COMMAND_SCAN_WIFI",
		29: "MORPHEUS_COMMAND_GET_NEXT_WIFI_AP",
		30: "MORPHEUS_COMMAND_LED_OPERATION_SUCCESS",
		31: "MORPHEUS_COMMAND_PUSH_DATA_AFTER_SET_TIMEZONE",
		32: "MORPHEUS_COMMAND_SET_COUNTRY_CODE",
		33: "MORPHEUS_COMMAND_SET_SERVER_IP",
		34: "MORPHEUS_COMMAND_CONNECTION_STATE",
		35: "MORPHEUS_COMMAND_PILL_PROX_DATA",
	}
	MorpheusCommand_CommandType_value = map[string]int32{
		"MORPHEUS_COMMAND_SET_TIME":                     0,
		"MORPHEUS_COMMAND_GET_TIME":                     1,
		"MORPHEUS_COMMAND_SET_WIFI_ENDPOINT":            2,
		"MORPHEUS_COMMAND_GET_WIFI_ENDPOINT":            3,
		"MORPHEUS_COMMAND_SET_ALARMS":                   4,
		"MORPHEUS_COMMAND_GET_ALARMS":                   5,
		"MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE":       6,
		"MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE":        7,
		"MORPHEUS_COMMAND_START_WIFISCAN":               8,
		"MORPHEUS_COMMAND_STOP_WIFISCAN":                9,
		"MORPHEUS_COMMAND_GET_DEVICE_ID":                10,
		"MORPHEUS_COMMAND_ERASE_PAIRED_PHONE":           11,
		"MORPHEUS_COMMAND_PAIR_PILL":                    12,
		"MORPHEUS_COMMAND_ERROR":                        13,
		"MORPHEUS_COMMAND_PAIR_SENSE":                   14,
		"MORPHEUS_COMMAND_UNPAIR_PILL":                  15,
		"MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN":           16,
		"MORPHEUS_COMMAND_PILL_DATA":                    17,
		"MORPHEUS_COMMAND_PILL_HEARTBEAT":               18,
		"MORPHEUS_COMMAND_PILL_DFU_BEGIN":               19,
		"MORPHEUS_COMMAND_FACTORY_RESET":                20,
		"MORPHEUS_COMMAND_PILL_SHAKES":                  21,
		"MORPHEUS_COMMAND_SYNC_DEVICE_ID":               22,
		"MORPHEUS_COMMAND_PHONE_BLE_CONNECTED":          23,
		"MORPHEUS_COMMAND_PHONE_BLE_BONDED":             24,
		"MORPHEUS_COMMAND_LED_BUSY":                     25,
		"MORPHEUS_COMMAND_LED_TRIPPY":                   26,
		"MORPHEUS_COMMAND_LED_OPERATION_FAILED":         27,
		"MORPHEUS_COMMAND_SCAN_WIFI":                    28,
		"MORPHEUS_COMMAND_GET_NEXT_WIFI_AP":             29,
		"MORPHEUS_COMMAND_LED_OPERATION_SUCCESS":        30,
		"MORPHEUS_COMMAND_PUSH_DATA_AFTER_SET_TIMEZONE": 31,
		"MORPHEUS_COMMAND_SET_COUNTRY_CODE":             32,
		"MORPHEUS_COMMAND_SET_SERVER_IP":                33,
		"MORPHEUS_COMMAND_CONNECTION_STATE":             34,
		"MORPHEUS_COMMAND_PILL_PROX_DATA":               35,
	}
)

func (x MorpheusCommand_CommandType) Enum() *MorpheusCommand_CommandType {
	p := new(MorpheusCommand_CommandType)
	*p = x
	return p
}

func (x MorpheusCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MorpheusCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_morpheus_ble_proto_enumTypes[3].Descriptor()
}

func (MorpheusCommand_CommandType) Type() protoreflect.EnumType {
	return &file_morpheus_ble_proto_enumTypes[3]
}

func (x MorpheusCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MorpheusCommand_CommandType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MorpheusCommand_CommandType(num)
	return nil
}

// Deprecated: Use MorpheusCommand_CommandType.Descriptor instead.
func (MorpheusCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{2, 0}
}

type WifiEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          *string                `protobuf:"bytes,1,req,name=ssid" json:"ssid,omitempty"`
	Bssid         []byte                 `protobuf:"bytes,2,opt,name=bssid" json:"bssid,omitempty"`
	Rssi          *int32                 `protobuf:"varint,4,req,name=rssi" json:"rssi,omitempty"`
	SecurityType  *WifiEndpointSecType   `protobuf:"varint,5,req,name=security_type,json=securityType,enum=WifiEndpointSecType" json:"security_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiEndpoint) Reset() {
	*x = WifiEndpoint{}
	mi := &file_morpheus_ble_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiEndpoint) ProtoMessage() {}

func (x *WifiEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_ble_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiEndpoint.ProtoReflect.Descriptor instead.
func (*WifiEndpoint) Descriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{0}
}

func (x *WifiEndpoint) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *WifiEndpoint) GetBssid() []byte {
	if x != nil {
		return x.Bssid
	}
	return nil
}

func (x *WifiEndpoint) GetRssi() int32 {
	if x != nil && x.Rssi != nil {
		return *x.Rssi
	}
	return 0
}

func (x *WifiEndpoint) GetSecurityType() WifiEndpointSecType {
	if x != nil && x.SecurityType != nil {
		return *x.SecurityType
	}
	return WifiEndpoint_SL_SCAN_SEC_TYPE_OPEN
}

type PillData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceId            *string                `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	BatteryLevel        *int32                 `protobuf:"varint,2,opt,name=battery_level,json=batteryLevel" json:"battery_level,omitempty"`
	Uptime              *int32                 `protobuf:"varint,3,opt,name=uptime" json:"uptime,omitempty"`
	MotionDataEntrypted []byte                 `protobuf:"bytes,4,opt,name=motion_data_entrypted,json=motionDataEntrypted" json:"motion_data_entrypted,omitempty"`
	ProtocolVersion     *int32                 `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	Timestamp           *uint64                `protobuf:"varint,6,req,name=timestamp" json:"timestamp,omitempty"` // In seconds
	Rssi                *int32                 `protobuf:"varint,7,opt,name=rssi" json:"rssi,omitempty"`
	FirmwareBuild       *int32                 `protobuf:"varint,8,opt,name=firmware_build,json=firmwareBuild" json:"firmware_build,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PillData) Reset() {
	*x = PillData{}
	mi := &file_morpheus_ble_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PillData) ProtoMessage() {}

func (x *PillData) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_ble_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PillData.ProtoReflect.Descriptor instead.
func (*PillData) Descriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{1}
}

func (x *PillData) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *PillData) GetBatteryLevel() int32 {
	if x != nil && x.BatteryLevel != nil {
		return *x.BatteryLevel
	}
	return 0
}

func (x *PillData) GetUptime() int32 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

func (x *PillData) GetMotionDataEntrypted() []byte {
	if x != nil {
		return x.MotionDataEntrypted
	}
	return nil
}

func (x *PillData) GetProtocolVersion() int32 {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return 0
}

func (x *PillData) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PillData) GetRssi() int32 {
	if x != nil && x.Rssi != nil {
		return *x.Rssi
	}
	return 0
}

func (x *PillData) GetFirmwareBuild() int32 {
	if x != nil && x.FirmwareBuild != nil {
		return *x.FirmwareBuild
	}
	return 0
}

type MorpheusCommand struct {
	state        protoimpl.MessageState       `protogen:"open.v1"`
	Version      *int32                       `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type         *MorpheusCommand_CommandType `protobuf:"varint,2,req,name=type,enum=MorpheusCommand_CommandType" json:"type,omitempty"`
	DeviceId     *string                      `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	AccountId    *string                      `protobuf:"bytes,4,opt,name=accountId" json:"accountId,omitempty"`         // Used by MORPHEUS_COMMAND_PAIR_PILL
	Error        *ErrorType                   `protobuf:"varint,5,opt,name=error,enum=ErrorType" json:"error,omitempty"` // MORPHEUS_COMMAND_ERROR
	WifiName     *string                      `protobuf:"bytes,6,opt,name=wifiName" json:"wifiName,omitempty"`
	WifiSSID     *string                      `protobuf:"bytes,7,opt,name=wifiSSID" json:"wifiSSID,omitempty"`
	WifiPassword *string                      `protobuf:"bytes,8,opt,name=wifiPassword" json:"wifiPassword,omitempty"`
	// optional int32 batteryLevel = 9;  // Removed field, dont reuse
	// optional int32 uptime = 10;       // Removed field, dont reuse
	// optional int32 motionData = 11;   // This field is removed, to make thing explicit, please DONOT remove the line
	// optional bytes motionDataEntrypted = 12;   // This field is removed, to make thing explicit, please DONOT remove the line
	ProtocolVersion     *int32               `protobuf:"varint,13,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	WifiScanResult      []*WifiEndpoint      `protobuf:"bytes,14,rep,name=wifi_scan_result,json=wifiScanResult" json:"wifi_scan_result,omitempty"`
	SecurityType        *WifiEndpointSecType `protobuf:"varint,15,opt,name=security_type,json=securityType,enum=WifiEndpointSecType" json:"security_type,omitempty"`
	PillData            *PillData            `protobuf:"bytes,16,opt,name=pill_data,json=pillData" json:"pill_data,omitempty"`
	WifiConnectionState *WifiConnectionState `protobuf:"varint,17,opt,name=wifi_connection_state,json=wifiConnectionState,enum=WifiConnectionState" json:"wifi_connection_state,omitempty"`
	BleBondCount        *int32               `protobuf:"varint,18,opt,name=ble_bond_count,json=bleBondCount" json:"ble_bond_count,omitempty"`
	CountryCode         *string              `protobuf:"bytes,19,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	AesKey              []byte               `protobuf:"bytes,20,opt,name=aes_key,json=aesKey" json:"aes_key,omitempty"`
	TopVersion          *string              `protobuf:"bytes,21,opt,name=top_version,json=topVersion" json:"top_version,omitempty"`
	ServerIp            *uint32              `protobuf:"varint,22,opt,name=server_ip,json=serverIp" json:"server_ip,omitempty"`
	SocketErrorCode     *uint32              `protobuf:"varint,23,opt,name=socket_error_code,json=socketErrorCode" json:"socket_error_code,omitempty"`
	HttpResponseCode    *string              `protobuf:"bytes,24,opt,name=http_response_code,json=httpResponseCode" json:"http_response_code,omitempty"`
	AppVersion          *int32               `protobuf:"varint,25,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	FirmwareBuild       *uint32              `protobuf:"varint,26,opt,name=firmware_build,json=firmwareBuild" json:"firmware_build,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MorpheusCommand) Reset() {
	*x = MorpheusCommand{}
	mi := &file_morpheus_ble_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MorpheusCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MorpheusCommand) ProtoMessage() {}

func (x *MorpheusCommand) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_ble_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MorpheusCommand.ProtoReflect.Descriptor instead.
func (*MorpheusCommand) Descriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{2}
}

func (x *MorpheusCommand) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *MorpheusCommand) GetType() MorpheusCommand_CommandType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MorpheusCommand_MORPHEUS_COMMAND_SET_TIME
}

func (x *MorpheusCommand) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *MorpheusCommand) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *MorpheusCommand) GetError() ErrorType {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorType_TIME_OUT
}

func (x *MorpheusCommand) GetWifiName() string {
	if x != nil && x.WifiName != nil {
		return *x.WifiName
	}
	return ""
}

func (x *MorpheusCommand) GetWifiSSID() string {
	if x != nil && x.WifiSSID != nil {
		return *x.WifiSSID
	}
	return ""
}

func (x *MorpheusCommand) GetWifiPassword() string {
	if x != nil && x.WifiPassword != nil {
		return *x.WifiPassword
	}
	return ""
}

func (x *MorpheusCommand) GetProtocolVersion() int32 {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return 0
}

func (x *MorpheusCommand) GetWifiScanResult() []*WifiEndpoint {
	if x != nil {
		return x.WifiScanResult
	}
	return nil
}

func (x *MorpheusCommand) GetSecurityType() WifiEndpointSecType {
	if x != nil && x.SecurityType != nil {
		return *x.SecurityType
	}
	return WifiEndpoint_SL_SCAN_SEC_TYPE_OPEN
}

func (x *MorpheusCommand) GetPillData() *PillData {
	if x != nil {
		return x.PillData
	}
	return nil
}

func (x *MorpheusCommand) GetWifiConnectionState() WifiConnectionState {
	if x != nil && x.WifiConnectionState != nil {
		return *x.WifiConnectionState
	}
	return WifiConnectionState_NO_WLAN_CONNECTED
}

func (x *MorpheusCommand) GetBleBondCount() int32 {
	if x != nil && x.BleBondCount != nil {
		return *x.BleBondCount
	}
	return 0
}

func (x *MorpheusCommand) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *MorpheusCommand) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *MorpheusCommand) GetTopVersion() string {
	if x != nil && x.TopVersion != nil {
		return *x.TopVersion
	}
	return ""
}

func (x *MorpheusCommand) GetServerIp() uint32 {
	if x != nil && x.ServerIp != nil {
		return *x.ServerIp
	}
	return 0
}

func (x *MorpheusCommand) GetSocketErrorCode() uint32 {
	if x != nil && x.SocketErrorCode != nil {
		return *x.SocketErrorCode
	}
	return 0
}

func (x *MorpheusCommand) GetHttpResponseCode() string {
	if x != nil && x.HttpResponseCode != nil {
		return *x.HttpResponseCode
	}
	return ""
}

func (x *MorpheusCommand) GetAppVersion() int32 {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return 0
}

func (x *MorpheusCommand) GetFirmwareBuild() uint32 {
	if x != nil && x.FirmwareBuild != nil {
		return *x.FirmwareBuild
	}
	return 0
}

type BatchedPillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pills         []*PillData            `protobuf:"bytes,1,rep,name=pills" json:"pills,omitempty"`
	DeviceId      *string                `protobuf:"bytes,2,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Prox          []*PillData            `protobuf:"bytes,3,rep,name=prox" json:"prox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchedPillData) Reset() {
	*x = BatchedPillData{}
	mi := &file_morpheus_ble_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchedPillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedPillData) ProtoMessage() {}

func (x *BatchedPillData) ProtoReflect() protoreflect.Message {
	mi := &file_morpheus_ble_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedPillData.ProtoReflect.Descriptor instead.
func (*BatchedPillData) Descriptor() ([]byte, []int) {
	return file_morpheus_ble_proto_rawDescGZIP(), []int{3}
}

func (x *BatchedPillData) GetPills() []*PillData {
	if x != nil {
		return x.Pills
	}
	return nil
}

func (x *BatchedPillData) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *BatchedPillData) GetProx() []*PillData {
	if x != nil {
		return x.Prox
	}
	return nil
}

var File_morpheus_ble_proto protoreflect.FileDescriptor

const file_morpheus_ble_proto_rawDesc = "" +
	"\n" +
	"\x12morpheus_ble.proto\"\xee\x03\n" +
	"\rwifi_endpoint\x12\x12\n" +
	"\x04ssid\x18\x01 \x02(\tR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x02 \x01(\fR\x05bssid\x12\x12\n" +
	"\x04rssi\x18\x04 \x02(\x05R\x04rssi\x12<\n" +
	"\rsecurity_type\x18\x05 \x02(\x0e2\x17.wifi_endpoint.sec_typeR\fsecurityType\"\xe0\x02\n" +
	"\bsec_type\x12\x19\n" +
	"\x15SL_SCAN_SEC_TYPE_OPEN\x10\x00\x12\x18\n" +
	"\x14SL_SCAN_SEC_TYPE_WEP\x10\x01\x12\x18\n" +
	"\x14SL_SCAN_SEC_TYPE_WPA\x10\x02\x12\x1c\n" +
	"\x18SL_WLAN_SEC_TYPE_WPS_PBC\x10\x03\x12\x1c\n" +
	"\x18SL_WLAN_SEC_TYPE_WPS_PIN\x10\x04\x12\x1c\n" +
	"\x18SL_WLAN_SEC_TYPE_WPA_ENT\x10\x05\x12\x1c\n" +
	"\x18SL_WLAN_SEC_TYPE_P2P_PBC\x10\x06\x12#\n" +
	"\x1fSL_WLAN_SEC_TYPE_P2P_PIN_KEYPAD\x10\a\x12$\n" +
	" SL_WLAN_SEC_TYPE_P2P_PIN_DISPLAY\x10\b\x12!\n" +
	"\x1dSL_WLAN_SEC_TYPE_P2P_PIN_AUTO\x10\t\x12\x1f\n" +
	"\x1bSL_WLAN_SEC_TYPE_WEP_SHARED\x10\n" +
	"\"\x9d\x02\n" +
	"\tpill_data\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x02(\tR\bdeviceId\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x05R\fbatteryLevel\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x05R\x06uptime\x122\n" +
	"\x15motion_data_entrypted\x18\x04 \x01(\fR\x13motionDataEntrypted\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\x05R\x0fprotocolVersion\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x02(\x04R\ttimestamp\x12\x12\n" +
	"\x04rssi\x18\a \x01(\x05R\x04rssi\x12%\n" +
	"\x0efirmware_build\x18\b \x01(\x05R\rfirmwareBuild\"\xb4\x11\n" +
	"\x0fMorpheusCommand\x12\x18\n" +
	"\aversion\x18\x01 \x02(\x05R\aversion\x120\n" +
	"\x04type\x18\x02 \x02(\x0e2\x1c.MorpheusCommand.CommandTypeR\x04type\x12\x1a\n" +
	"\bdeviceId\x18\x03 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\taccountId\x18\x04 \x01(\tR\taccountId\x12 \n" +
	"\x05error\x18\x05 \x01(\x0e2\n" +
	".ErrorTypeR\x05error\x12\x1a\n" +
	"\bwifiName\x18\x06 \x01(\tR\bwifiName\x12\x1a\n" +
	"\bwifiSSID\x18\a \x01(\tR\bwifiSSID\x12\"\n" +
	"\fwifiPassword\x18\b \x01(\tR\fwifiPassword\x12)\n" +
	"\x10protocol_version\x18\r \x01(\x05R\x0fprotocolVersion\x128\n" +
	"\x10wifi_scan_result\x18\x0e \x03(\v2\x0e.wifi_endpointR\x0ewifiScanResult\x12<\n" +
	"\rsecurity_type\x18\x0f \x01(\x0e2\x17.wifi_endpoint.sec_typeR\fsecurityType\x12'\n" +
	"\tpill_data\x18\x10 \x01(\v2\n" +
	".pill_dataR\bpillData\x12J\n" +
	"\x15wifi_connection_state\x18\x11 \x01(\x0e2\x16.wifi_connection_stateR\x13wifiConnectionState\x12$\n" +
	"\x0eble_bond_count\x18\x12 \x01(\x05R\fbleBondCount\x12!\n" +
	"\fcountry_code\x18\x13 \x01(\tR\vcountryCode\x12\x17\n" +
	"\aaes_key\x18\x14 \x01(\fR\x06aesKey\x12\x1f\n" +
	"\vtop_version\x18\x15 \x01(\tR\n" +
	"topVersion\x12\x1b\n" +
	"\tserver_ip\x18\x16 \x01(\rR\bserverIp\x12*\n" +
	"\x11socket_error_code\x18\x17 \x01(\rR\x0fsocketErrorCode\x12,\n" +
	"\x12http_response_code\x18\x18 \x01(\tR\x10httpResponseCode\x12\x1f\n" +
	"\vapp_version\x18\x19 \x01(\x05R\n" +
	"appVersion\x12%\n" +
	"\x0efirmware_build\x18\x1a \x01(\rR\rfirmwareBuild\"\xc2\n" +
	"\n" +
	"\vCommandType\x12\x1d\n" +
	"\x19MORPHEUS_COMMAND_SET_TIME\x10\x00\x12\x1d\n" +
	"\x19MORPHEUS_COMMAND_GET_TIME\x10\x01\x12&\n" +
	"\"MORPHEUS_COMMAND_SET_WIFI_ENDPOINT\x10\x02\x12&\n" +
	"\"MORPHEUS_COMMAND_GET_WIFI_ENDPOINT\x10\x03\x12\x1f\n" +
	"\x1bMORPHEUS_COMMAND_SET_ALARMS\x10\x04\x12\x1f\n" +
	"\x1bMORPHEUS_COMMAND_GET_ALARMS\x10\x05\x12+\n" +
	"'MORPHEUS_COMMAND_SWITCH_TO_PAIRING_MODE\x10\x06\x12*\n" +
	"&MORPHEUS_COMMAND_SWITCH_TO_NORMAL_MODE\x10\a\x12#\n" +
	"\x1fMORPHEUS_COMMAND_START_WIFISCAN\x10\b\x12\"\n" +
	"\x1eMORPHEUS_COMMAND_STOP_WIFISCAN\x10\t\x12\"\n" +
	"\x1eMORPHEUS_COMMAND_GET_DEVICE_ID\x10\n" +
	"\x12'\n" +
	"#MORPHEUS_COMMAND_ERASE_PAIRED_PHONE\x10\v\x12\x1e\n" +
	"\x1aMORPHEUS_COMMAND_PAIR_PILL\x10\f\x12\x1a\n" +
	"\x16MORPHEUS_COMMAND_ERROR\x10\r\x12\x1f\n" +
	"\x1bMORPHEUS_COMMAND_PAIR_SENSE\x10\x0e\x12 \n" +
	"\x1cMORPHEUS_COMMAND_UNPAIR_PILL\x10\x0f\x12'\n" +
	"#MORPHEUS_COMMAND_MORPHEUS_DFU_BEGIN\x10\x10\x12\x1e\n" +
	"\x1aMORPHEUS_COMMAND_PILL_DATA\x10\x11\x12#\n" +
	"\x1fMORPHEUS_COMMAND_PILL_HEARTBEAT\x10\x12\x12#\n" +
	"\x1fMORPHEUS_COMMAND_PILL_DFU_BEGIN\x10\x13\x12\"\n" +
	"\x1eMORPHEUS_COMMAND_FACTORY_RESET\x10\x14\x12 \n" +
	"\x1cMORPHEUS_COMMAND_PILL_SHAKES\x10\x15\x12#\n" +
	"\x1fMORPHEUS_COMMAND_SYNC_DEVICE_ID\x10\x16\x12(\n" +
	"$MORPHEUS_COMMAND_PHONE_BLE_CONNECTED\x10\x17\x12%\n" +
	"!MORPHEUS_COMMAND_PHONE_BLE_BONDED\x10\x18\x12\x1d\n" +
	"\x19MORPHEUS_COMMAND_LED_BUSY\x10\x19\x12\x1f\n" +
	"\x1bMORPHEUS_COMMAND_LED_TRIPPY\x10\x1a\x12)\n" +
	"%MORPHEUS_COMMAND_LED_OPERATION_FAILED\x10\x1b\x12\x1e\n" +
	"\x1aMORPHEUS_COMMAND_SCAN_WIFI\x10\x1c\x12%\n" +
	"!MORPHEUS_COMMAND_GET_NEXT_WIFI_AP\x10\x1d\x12*\n" +
	"&MORPHEUS_COMMAND_LED_OPERATION_SUCCESS\x10\x1e\x121\n" +
	"-MORPHEUS_COMMAND_PUSH_DATA_AFTER_SET_TIMEZONE\x10\x1f\x12%\n" +
	"!MORPHEUS_COMMAND_SET_COUNTRY_CODE\x10 \x12\"\n" +
	"\x1eMORPHEUS_COMMAND_SET_SERVER_IP\x10!\x12%\n" +
	"!MORPHEUS_COMMAND_CONNECTION_STATE\x10\"\x12#\n" +
	"\x1fMORPHEUS_COMMAND_PILL_PROX_DATA\x10#\"r\n" +
	"\x11batched_pill_data\x12 \n" +
	"\x05pills\x18\x01 \x03(\v2\n" +
	".pill_dataR\x05pills\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x02(\tR\bdeviceId\x12\x1e\n" +
	"\x04prox\x18\x03 \x03(\v2\n" +
	".pill_dataR\x04prox*\xa7\x03\n" +
	"\tErrorType\x12\f\n" +
	"\bTIME_OUT\x10\x00\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x01\x12\x19\n" +
	"\x15DEVICE_ALREADY_PAIRED\x10\x02\x12\x17\n" +
	"\x13INTERNAL_DATA_ERROR\x10\x03\x12\x18\n" +
	"\x14DEVICE_DATABASE_FULL\x10\x04\x12\x14\n" +
	"\x10DEVICE_NO_MEMORY\x10\x05\x12\x1d\n" +
	"\x19INTERNAL_OPERATION_FAILED\x10\x06\x12\x18\n" +
	"\x14NO_ENDPOINT_IN_RANGE\x10\a\x12\x19\n" +
	"\x15WLAN_CONNECTION_ERROR\x10\b\x12\x15\n" +
	"\x11FAIL_TO_OBTAIN_IP\x10\t\x12\x1f\n" +
	"\x1bWLAN_ENDPOINT_DELETE_FAILED\x10\n" +
	"\x12\x16\n" +
	"\x12INVALID_ACCOUNT_ID\x10\v\x12\x1a\n" +
	"\x16FORCE_DATA_PUSH_FAILED\x10\f\x12\x1a\n" +
	"\x16PROTOBUF_ENCODE_FAILED\x10\r\x12\x1a\n" +
	"\x16PROTOBUF_DECODE_FAILED\x10\x0e\x12\x1d\n" +
	"\x19SERVER_CONNECTION_TIMEOUT\x10\x0f*\xf8\x01\n" +
	"\x15wifi_connection_state\x12\x15\n" +
	"\x11NO_WLAN_CONNECTED\x10\x00\x12\x13\n" +
	"\x0fWLAN_CONNECTING\x10\x01\x12\x12\n" +
	"\x0eWLAN_CONNECTED\x10\x02\x12\x10\n" +
	"\fIP_RETRIEVED\x10\x03\x12\x10\n" +
	"\fDNS_RESOLVED\x10\x04\x12\x14\n" +
	"\x10SOCKET_CONNECTED\x10\x05\x12\x10\n" +
	"\fREQUEST_SENT\x10\x06\x12\r\n" +
	"\tCONNECTED\x10\a\x12\f\n" +
	"\bSSL_FAIL\x10\b\x12\x12\n" +
	"\x0eHELLO_KEY_FAIL\x10\t\x12\x0e\n" +
	"\n" +
	"DNS_FAILED\x10\n" +
	"\x12\x12\n" +
	"\x0eCONNECT_FAILED\x10\vBg\n" +
	"\x18com.hello.suripu.api.bleB\x12SenseCommandProtosZ7github.com/josephspurrier/hello-orb/orb/internal/pb/ble"

var (
	file_morpheus_ble_proto_rawDescOnce sync.Once
	file_morpheus_ble_proto_rawDescData []byte
)

func file_morpheus_ble_proto_rawDescGZIP() []byte {
	file_morpheus_ble_proto_rawDescOnce.Do(func() {
		file_morpheus_ble_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_morpheus_ble_proto_rawDesc), len(file_morpheus_ble_proto_rawDesc)))
	})
	return file_morpheus_ble_proto_rawDescData
}

var file_morpheus_ble_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_morpheus_ble_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_morpheus_ble_proto_goTypes = []any{
	(ErrorType)(0),                   // 0: ErrorType
	(WifiConnectionState)(0),         // 1: wifi_connection_state
	(WifiEndpointSecType)(0),         // 2: wifi_endpoint.sec_type
	(MorpheusCommand_CommandType)(0), // 3: MorpheusCommand.CommandType
	(*WifiEndpoint)(nil),             // 4: wifi_endpoint
	(*PillData)(nil),                 // 5: pill_data
	(*MorpheusCommand)(nil),          // 6: MorpheusCommand
	(*BatchedPillData)(nil),          // 7: batched_pill_data
}
var file_morpheus_ble_proto_depIdxs = []int32{
	2, // 0: wifi_endpoint.security_type:type_name -> wifi_endpoint.sec_type
	3, // 1: MorpheusCommand.type:type_name -> MorpheusCommand.CommandType
	0, // 2: MorpheusCommand.error:type_name -> ErrorType
	4, // 3: MorpheusCommand.wifi_scan_result:type_name -> wifi_endpoint
	2, // 4: MorpheusCommand.security_type:type_name -> wifi_endpoint.sec_type
	5, // 5: MorpheusCommand.pill_data:type_name -> pill_data
	1, // 6: MorpheusCommand.wifi_connection_state:type_name -> wifi_connection_state
	5, // 7: batched_pill_data.pills:type_name -> pill_data
	5, // 8: batched_pill_data.prox:type_name -> pill_data
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_morpheus_ble_proto_init() }
func file_morpheus_ble_proto_init() {
	if File_morpheus_ble_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_morpheus_ble_proto_rawDesc), len(file_morpheus_ble_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_morpheus_ble_proto_goTypes,
		DependencyIndexes: file_morpheus_ble_proto_depIdxs,
		EnumInfos:         file_morpheus_ble_proto_enumTypes,
		MessageInfos:      file_morpheus_ble_proto_msgTypes,
	}.Build()
	File_morpheus_ble_proto = out.File
	file_morpheus_ble_proto_goTypes = nil
	file_morpheus_ble_proto_depIdxs = nil
}
